CURRENT_STORY = nil
SCREENSHOTS = {}
MAX_ACTIONS = 10000
STATIC_CAMERA = true
LOG_DATA = false
LOG_FREQUENCY = 1000 / 30 --in milliseconds
DEBUG = true
DEBUG_LOGGER = false
DEBUG_OBJECTS = false
DEBUG_EPISODE = true
PRIORITIZE_CAMERA = 'barroom'
DEBUG_ACTIONS = true
FREE_ROAM = false
TIME_STAMP = false
ACTORS_CROWDING_FACTOR = 0
LOAD_FROM_GRAPH = true
INPUT_GRAPHS = {'example_graph1'}
INPUT_FOLDER = "story_generator/samples_babi/"
GRAPH = {
}
PED_ZOO = {}