using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using SyntheticVideo2language.StoryGenerator.Api;
using Vision2language.StoryGenerator.Api;

namespace SampSharp.SyntheticGameMode.Story.Actions
{
    public class SetPlayerSkin : IGenericStoryItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int TopologicalOrder { get; set; }

        public static readonly List<SetPlayerSkin> PlayerSkins = new List<SetPlayerSkin>
        {
            //new SetPlayerSkin(0, "Carl \"CJ\" Johnson"),
            //new SetPlayerSkin(1, "The Truth"),
            //new SetPlayerSkin(2, "Maccer"),
            //new SetPlayerSkin(3, "Andre"),
            //new SetPlayerSkin(4, "Barry \"Big Bear\" Thorne[Thin]"),
            //new SetPlayerSkin(5, "Barry \"Big Bear\" Thorne[Big]"),
            //new SetPlayerSkin(6, "Emmet"),
            new SetPlayerSkin(7, "Black man in a blue jeans jacket and beige pants"),
            //new SetPlayerSkin(8, "Janitor"),
            //new SetPlayerSkin(9, "Normal Ped"),
            new SetPlayerSkin(10, "Old Woman"),
            //new SetPlayerSkin(11, "Casino croupier"),
            //new SetPlayerSkin(12, "Rich Woman"),
            //new SetPlayerSkin(13, "Street Girl"),
            //new SetPlayerSkin(14, "Normal Ped"),
            //new SetPlayerSkin(15, "Mr.Whittaker(RS Haul Owner)"),
            //new SetPlayerSkin(16, "Airport Ground Worker"),
            //new SetPlayerSkin(17, "Businessman"),
            new SetPlayerSkin(18, "Tall black man in red shorts"),
            //new SetPlayerSkin(19, "DJ"),
            //new SetPlayerSkin(20, "Rich Guy(Madd Dogg's Manager)"),
            //new SetPlayerSkin(21, "Normal Ped"),
            //new SetPlayerSkin(22, "Normal Ped"),
            //new SetPlayerSkin(23, "BMXer"),
            //new SetPlayerSkin(24, "Madd Dogg Bodyguard"),
            //new SetPlayerSkin(25, "Madd Dogg Bodyguard"),
            //new SetPlayerSkin(26, "Backpacker"),
            //new SetPlayerSkin(27, "Construction Worker"),
            //new SetPlayerSkin(28, "Drug Dealer"),
            //new SetPlayerSkin(29, "Drug Dealer"),
            //new SetPlayerSkin(30, "Drug Dealer"),
            //new SetPlayerSkin(31, "Farm - Town inhabitant"),
            //new SetPlayerSkin(32, "Farm - Town inhabitant"),
            //new SetPlayerSkin(33, "Farm - Town inhabitant"),
            //new SetPlayerSkin(34, "Farm - Town inhabitant"),
            //new SetPlayerSkin(35, "Gardener"),
            //new SetPlayerSkin(36, "Golfer"),
            //new SetPlayerSkin(37, "Golfer"),
            //new SetPlayerSkin(38, "Normal Ped"),
            //new SetPlayerSkin(39, "Normal Ped"),
            //new SetPlayerSkin(40, "Normal Ped"),
            //new SetPlayerSkin(41, "Normal Ped"),
            //new SetPlayerSkin(42, "Jethro"),
            //new SetPlayerSkin(43, "Normal Ped"),
            //new SetPlayerSkin(44, "Normal Ped"),
            new SetPlayerSkin(45, "White man with glasses wearing green shorts"),
            //new SetPlayerSkin(46, "Normal Ped"),
            //new SetPlayerSkin(47, "Normal Ped"),
            //new SetPlayerSkin(48, "Normal Ped"),
            //new SetPlayerSkin(49, "Snakehead(Da Nang)"),
            //new SetPlayerSkin(50, "Mechanic"),
            //new SetPlayerSkin(51, "Mountain Biker"),
            //new SetPlayerSkin(52, "Mountain Biker"),
            //new SetPlayerSkin(53, "Unknown"),
            //new SetPlayerSkin(54, "Normal Ped"),
            //new SetPlayerSkin(55, "Normal Ped"),
            //new SetPlayerSkin(56, "Normal Ped"),
            //new SetPlayerSkin(57, "Oriental Ped"),
            //new SetPlayerSkin(58, "Oriental Ped"),
            //new SetPlayerSkin(59, "Normal Ped"),
            //new SetPlayerSkin(60, "Normal Ped"),
            new SetPlayerSkin(61, "Pilot"),
            //new SetPlayerSkin(62, "Colonel Fuhrberger"),
            ////new SetPlayerSkin(63, "Prostitute"),
            ////new SetPlayerSkin(64, "Prostitute"),
            //new SetPlayerSkin(65, "Kendl Johnson"),
            //new SetPlayerSkin(66, "Pool Player"),
            //new SetPlayerSkin(67, "Pool Player"),
            //new SetPlayerSkin(68, "Priest / Preacher"),
            //new SetPlayerSkin(69, "Normal Ped"),
            //new SetPlayerSkin(70, "Scientist"),
            //new SetPlayerSkin(71, "Security Guard"),
            //new SetPlayerSkin(72, "Hippy"),
            //new SetPlayerSkin(73, "Hippy"),
            //new SetPlayerSkin(74, "-"),
            ////new SetPlayerSkin(75, "Prostitute"),
            //new SetPlayerSkin(76, "Stewardess"),
            //new SetPlayerSkin(77, "Homeless"),
            //new SetPlayerSkin(78, "Homeless"),
            //new SetPlayerSkin(79, "Homeless"),
            //new SetPlayerSkin(80, "Boxer"),
            //new SetPlayerSkin(81, "Boxer"),
            //new SetPlayerSkin(82, "Black Elvis"),
            //new SetPlayerSkin(83, "White Elvis"),
            //new SetPlayerSkin(84, "Blue Elvis"),
            ////new SetPlayerSkin(85, "Prostitute"),
            //new SetPlayerSkin(86, "Ryder with robbery mask"),
            //new SetPlayerSkin(87, "Stripper"),
            //new SetPlayerSkin(88, "Normal Ped"),
            //new SetPlayerSkin(89, "Normal Ped"),
            //new SetPlayerSkin(90, "Jogger"),
            //new SetPlayerSkin(91, "Rich Woman"),
            //new SetPlayerSkin(92, "Rollerskater"),
            //new SetPlayerSkin(93, "Normal Ped"),
            //new SetPlayerSkin(94, "Normal Ped"),
            //new SetPlayerSkin(95, "Normal Ped, Works at or owns Dillimore Gas Station"),
            //new SetPlayerSkin(96, "Jogger"),
            new SetPlayerSkin(97, "White blond male in red shorts"),
            //new SetPlayerSkin(98, "Normal Ped"),
            //new SetPlayerSkin(99, "Rollerskater"),
            //new SetPlayerSkin(100, "Biker"),
            //new SetPlayerSkin(101, "Normal Ped"),
            //new SetPlayerSkin(102, "Balla"),
            //new SetPlayerSkin(103, "Balla"),
            //new SetPlayerSkin(104, "Balla"),
            //new SetPlayerSkin(105, "Grove Street Families"),
            //new SetPlayerSkin(106, "Grove Street Families"),
            //new SetPlayerSkin(107, "Grove Street Families"),
            //new SetPlayerSkin(108, "Los Santos Vagos"),
            //new SetPlayerSkin(109, "Los Santos Vagos"),
            //new SetPlayerSkin(110, "Los Santos Vagos"),
            //new SetPlayerSkin(111, "The Russian Mafia"),
            //new SetPlayerSkin(112, "The Russian Mafia"),
            //new SetPlayerSkin(113, "The Russian Mafia"),
            //new SetPlayerSkin(114, "Varios Los Aztecas"),
            //new SetPlayerSkin(115, "Varios Los Aztecas"),
            //new SetPlayerSkin(116, "Varios Los Aztecas"),
            //new SetPlayerSkin(117, "Triad"),
            //new SetPlayerSkin(118, "Triad"),
            //new SetPlayerSkin(119, "Johhny Sindacco"),
            //new SetPlayerSkin(120, "Triad Boss"),
            //new SetPlayerSkin(121, "Da Nang Boy"),
            //new SetPlayerSkin(122, "Da Nang Boy"),
            //new SetPlayerSkin(123, "Da Nang Boy"),
            //new SetPlayerSkin(124, "The Mafia"),
            //new SetPlayerSkin(125, "The Mafia"),
            //new SetPlayerSkin(126, "The Mafia"),
            //new SetPlayerSkin(127, "The Mafia"),
            //new SetPlayerSkin(128, "Farm Inhabitant"),
            //new SetPlayerSkin(129, "Farm Inhabitant"),
            //new SetPlayerSkin(130, "Farm Inhabitant"),
            //new SetPlayerSkin(131, "Farm Inhabitant"),
            //new SetPlayerSkin(132, "Farm Inhabitant"),
            //new SetPlayerSkin(133, "Farm Inhabitant"),
            //new SetPlayerSkin(134, "Homeless"),
            //new SetPlayerSkin(135, "Homeless"),
            //new SetPlayerSkin(136, "Normal Ped"),
            //new SetPlayerSkin(137, "Homeless"),
            new SetPlayerSkin(138, "White woman in a swim suit"),
            new SetPlayerSkin(139, "Black woman in a swim suit"),
            new SetPlayerSkin(140, "Asian woman in a swim suit"),
            //new SetPlayerSkin(141, "Businesswoman"),
            //new SetPlayerSkin(142, "Taxi Driver"),
            //new SetPlayerSkin(143, "Crack Maker"),
            //new SetPlayerSkin(144, "Crack Maker"),
            //new SetPlayerSkin(145, "Crack Maker"),
            //new SetPlayerSkin(146, "Crack Maker"),
            new SetPlayerSkin(147, "Businessman in a suit"),
            //new SetPlayerSkin(148, "Businesswoman wearing a blazer and pants suit"), //can't lay on ground (beach)
            //new SetPlayerSkin(149, "Big Smoke Armored"),
            new SetPlayerSkin(150, "Businesswoman wearing a blazer and skirt suit"),
            //new SetPlayerSkin(151, "Normal Ped"),
            ////new SetPlayerSkin(152, "Prostitute"),
            //new SetPlayerSkin(153, "Construction Worker"),
            //new SetPlayerSkin(154, "Beach Visitor"),
            //new SetPlayerSkin(155, "Well Stacked Pizza Worker"),
            //new SetPlayerSkin(156, "Barber"),
            //new SetPlayerSkin(157, "Hillbilly"),
            //new SetPlayerSkin(158, "Farmer"),
            //new SetPlayerSkin(159, "Hillbilly"),
            //new SetPlayerSkin(160, "Hillbilly"),
            //new SetPlayerSkin(161, "Farmer"),
            //new SetPlayerSkin(162, "Hillbilly"),
            //new SetPlayerSkin(163, "Black Bouncer"),
            //new SetPlayerSkin(164, "White Bouncer"),
            //new SetPlayerSkin(165, "White MIB agent"),
            //new SetPlayerSkin(166, "Black MIB agent"),
            //new SetPlayerSkin(167, "Cluckin' Bell Worker"),
            //new SetPlayerSkin(168, "Hotdog / Chilli Dog Vendor"),
            //new SetPlayerSkin(169, "Normal Ped"),
            //new SetPlayerSkin(170, "Normal Ped"),
            //new SetPlayerSkin(171, "Blackjack Dealer"),
            //new SetPlayerSkin(172, "Casino croupier"),
            //new SetPlayerSkin(173, "San Fierro Rifa"),
            //new SetPlayerSkin(174, "San Fierro Rifa"),
            //new SetPlayerSkin(175, "San Fierro Rifa"),
            //new SetPlayerSkin(176, "Barber"),
            //new SetPlayerSkin(177, "Barber"),
            //new SetPlayerSkin(178, "Whore"),
            //new SetPlayerSkin(179, "Ammunation Salesman"),
            //new SetPlayerSkin(180, "Tattoo Artist"),
            //new SetPlayerSkin(181, "Punk"),
            //new SetPlayerSkin(182, "Cab Driver"),
            //new SetPlayerSkin(183, "Normal Ped"),
            //new SetPlayerSkin(184, "Normal Ped"),
            //new SetPlayerSkin(185, "Normal Ped"),
            //new SetPlayerSkin(186, "Normal Ped"),
            //new SetPlayerSkin(187, "Businessman"),
            //new SetPlayerSkin(188, "Normal Ped"),
            //new SetPlayerSkin(189, "Valet"),
            //new SetPlayerSkin(190, "Barbara Schternvart"),
            //new SetPlayerSkin(191, "Helena Wankstein"),
            //new SetPlayerSkin(192, "Michelle Cannes"),
            //new SetPlayerSkin(193, "Katie Zhan"),
            //new SetPlayerSkin(194, "Millie Perkins"),
            //new SetPlayerSkin(195, "Denise Robinson"),
            //new SetPlayerSkin(196, "Farm - Town inhabitant"),
            //new SetPlayerSkin(197, "Hillbilly"),
            //new SetPlayerSkin(198, "Farm - Town inhabitant"),
            //new SetPlayerSkin(199, "Farm - Town inhabitant"),
            //new SetPlayerSkin(200, "Hillbilly"),
            //new SetPlayerSkin(201, "Farmer"),
            //new SetPlayerSkin(202, "Farmer"),
            //new SetPlayerSkin(203, "Karate Teacher"),
            //new SetPlayerSkin(204, "Karate Teacher"),
            //new SetPlayerSkin(205, "Burger Shot Cashier"),
            //new SetPlayerSkin(206, "Cab Driver"),
            ////new SetPlayerSkin(207, "Prostitute"),
            //new SetPlayerSkin(208, "Su Xi Mu(Suzie)"),
            //new SetPlayerSkin(209, "Oriental Noodle stand vendor"),
            //new SetPlayerSkin(210, "Oriental Boating School Instructor"),
            //new SetPlayerSkin(211, "Clothes shop staff"),
            //new SetPlayerSkin(212, "Homeless"),
            //new SetPlayerSkin(213, "Weird old man"),
            //new SetPlayerSkin(214, "Waitress(Maria Latore)"),
            //new SetPlayerSkin(215, "Normal Ped"),
            //new SetPlayerSkin(216, "Normal Ped"),
            //new SetPlayerSkin(217, "Clothes shop staff"),
            //new SetPlayerSkin(218, "Normal Ped"),
            //new SetPlayerSkin(219, "Rich Woman"),
            //new SetPlayerSkin(220, "Cab Driver"),
            //new SetPlayerSkin(221, "Normal Ped"),
            //new SetPlayerSkin(222, "Normal Ped"),
            //new SetPlayerSkin(223, "Normal Ped"),
            //new SetPlayerSkin(224, "Normal Ped"),
            //new SetPlayerSkin(225, "Normal Ped"),
            //new SetPlayerSkin(226, "Normal Ped"),
            //new SetPlayerSkin(227, "Oriental Businessman"),
            //new SetPlayerSkin(228, "Oriental Ped"),
            //new SetPlayerSkin(229, "Oriental Ped"),
            //new SetPlayerSkin(230, "Homeless"),
            //new SetPlayerSkin(231, "Normal Ped"),
            //new SetPlayerSkin(232, "Normal Ped"),
            //new SetPlayerSkin(233, "Normal Ped"),
            //new SetPlayerSkin(234, "Cab Driver"),
            //new SetPlayerSkin(235, "Normal Ped"),
            //new SetPlayerSkin(236, "Normal Ped"),
            ////new SetPlayerSkin(237, "Prostitute"),
            ////new SetPlayerSkin(238, "Prostitute"),
            //new SetPlayerSkin(239, "Homeless"),
            //new SetPlayerSkin(240, "The D.A"),
            //new SetPlayerSkin(241, "Afro - American"),
            //new SetPlayerSkin(242, "Mexican"),
            ////new SetPlayerSkin(243, "Prostitute"),
            //new SetPlayerSkin(244, "Stripper"),
            ////new SetPlayerSkin(245, "Prostitute"),
            //new SetPlayerSkin(246, "Stripper"),
            //new SetPlayerSkin(247, "Biker"),
            //new SetPlayerSkin(248, "Biker"),
            //new SetPlayerSkin(249, "Pimp"),
            //new SetPlayerSkin(250, "Normal Ped"),
            //new SetPlayerSkin(251, "Lifeguard"),
            //new SetPlayerSkin(252, "Naked Valet"),
            //new SetPlayerSkin(253, "Bus Driver"),
            //new SetPlayerSkin(254, "Biker Drug Dealer"),
            //new SetPlayerSkin(255, "Chauffeur(Limo Driver)"),
            //new SetPlayerSkin(256, "Stripper"),
            //new SetPlayerSkin(257, "Stripper"),
            //new SetPlayerSkin(258, "Heckler"),
            //new SetPlayerSkin(259, "Heckler"),
            //new SetPlayerSkin(260, "Construction Worker"),
            //new SetPlayerSkin(261, "Cab driver"),
            //new SetPlayerSkin(262, "Cab driver"),
            //new SetPlayerSkin(263, "Normal Ped"),
            //new SetPlayerSkin(264, "Clown(Ice - cream Van Driver)"),
            //new SetPlayerSkin(265, "Officer Frank Tenpenny(Corrupt Cop)"),
            //new SetPlayerSkin(266, "Officer Eddie Pulaski(Corrupt Cop)"),
            //new SetPlayerSkin(267, "Officer Jimmy Hernandez"),
            //new SetPlayerSkin(268, "Dwaine / Dwayne"),
            //new SetPlayerSkin(269, "Melvin \"Big Smoke\" Harris"),
            //new SetPlayerSkin(270, "Sean 'Sweet' Johnson"),
            //new SetPlayerSkin(271, "Lance 'Ryder' Wilson"),
            //new SetPlayerSkin(272, "Mafia Boss"),
            //new SetPlayerSkin(273, "T - Bone Mendez"),
            //new SetPlayerSkin(274, "Paramedic(Emergency Medical Technician)"),
            //new SetPlayerSkin(275, "Paramedic(Emergency Medical Technician)"),
            //new SetPlayerSkin(276, "Paramedic(Emergency Medical Technician)"),
            //new SetPlayerSkin(277, "Firefighter"),
            //new SetPlayerSkin(278, "Firefighter"),
            //new SetPlayerSkin(279, "Firefighter"),
            //new SetPlayerSkin(280, "Los Santos Police Officer"),
            //new SetPlayerSkin(281, "San Fierro Police Officer"),
            //new SetPlayerSkin(282, "Las Venturas Police Officer"),
            //new SetPlayerSkin(283, "County Sheriff"),
            //new SetPlayerSkin(284, "LSPD Motorbike Cop"),
            //new SetPlayerSkin(285, "S.W.A.T Special Forces"),
            //new SetPlayerSkin(286, "Federal Agent"),
            //new SetPlayerSkin(287, "San Andreas Army"),
            //new SetPlayerSkin(288, "Desert Sheriff"),
            //new SetPlayerSkin(289, "Zero"),
            //new SetPlayerSkin(290, "Ken Rosenberg"),
            //new SetPlayerSkin(291, "Kent Paul"),
            //new SetPlayerSkin(292, "Cesar Vialpando"),
            //new SetPlayerSkin(293, "Jeffery \"OG Loc\" Martin / Cross"),
            //new SetPlayerSkin(294, "Wu Zi Mu(Woozie)"),
            //new SetPlayerSkin(295, "Michael Toreno"),
            //new SetPlayerSkin(296, "Jizzy B."),
            //new SetPlayerSkin(297, "Madd Dogg"),
            //new SetPlayerSkin(298, "Catalina"),
            //new SetPlayerSkin(299, "Claude Speed"),
            //new SetPlayerSkin(300, "Los Santos Police Officer(Without gun holster)"),
            //new SetPlayerSkin(301, "San Fierro Police Officer(Without gun holster)"),
            //new SetPlayerSkin(302, "Las Venturas Police Officer(Without gun holster)"),
            //new SetPlayerSkin(303, "Los Santos Police Officer(Without uniform)"),
            //new SetPlayerSkin(304, "Los Santos Police Officer(Without uniform)"),
            //new SetPlayerSkin(305, "Las Venturas Police Officer(Without uniform)"),
            //new SetPlayerSkin(306, "Los Santos Police Officer"),
            //new SetPlayerSkin(307, "San Fierro Police Officer"),
            //new SetPlayerSkin(308, "San Fierro Paramedic(Emergency Medical Technician)"),
            //new SetPlayerSkin(309, "Las Venturas Police Officer"),
            //new SetPlayerSkin(310, "Country Sheriff(Without hat)"),
            //new SetPlayerSkin(311, "Desert Sheriff(Without hat)"),
        };

        public eStoryItemType StoryItemType => eStoryItemType.Action;

        public List<IGenericStoryItem> StoryItems { get; set; }

        public async Task<bool> ApplyInGameAsync(params object[] parameters)
        {
            if (parameters.Length < 1)
            {
                return false;
            }

            var player = parameters[0] as Player;
            await Task.Delay(100);
            player.Skin = this.Id;
            player.PlayerSkin = this;
            await Task.Delay(100);
            return true;
        }

        private SetPlayerSkin(int id, string description)
        {
            this.Id = id;
            this.Description = description;
        }
    }
}
