--See https://wiki.multitheftauto.com/wiki/Character_Skins for details
SetPlayerSkin = class(StoryActionBase, function(o, id, description, gender) --maybe add gender here
    StoryActionBase.init(o, {description = description})
    o.Id = id
    o.Gender = gender
    o.Nominative = 'he'
    o.Genitive = 'his'
    if gender == 2 then
        o.Nominative = 'she'
        o.Genitive = 'her'
    end
    o.isTaken = false
end)

SetPlayerSkin.MaleNames = {
'Liam',
'Noah',
'William',
'James',
'Logan',
'Benjamin',
'Mason',
'Elijah',
'Oliver',
'Jacob',
'Lucas',
'Michael',
'Alexander',
'Ethan',
'Daniel',
'Matthew',
'Aiden',
'Henry',
'Joseph',
'Jackson',
'Samuel',
'Sebastian',
'David',
'Carter',
'Wyatt',
'Jayden',
'John',
'Owen',
'Dylan',
'Luke',
'Gabriel',
'Anthony',
'Isaac',
'Grayson',
'Jack',
'Julian',
'Levi',
'Christopher',
'Joshua',
'Andrew',
'Lincoln',
'Mateo',
'Ryan',
'Jaxon',
'Nathan',
'Aaron',
'Isaiah',
'Thomas',
'Charles',
'Caleb',
'Josiah',
'Christian',
'Hunter',
'Eli',
'Jonathan',
'Connor',
'Landon',
'Adrian',
'Asher',
'Cameron',
'Leo',
'Theodore',
'Jeremiah',
'Hudson',
'Robert',
'Easton',
'Nolan',
'Nicholas',
'Ezra',
'Colton',
'Angel',
'Brayden',
'Jordan',
'Dominic',
'Austin',
'Ian',
'Adam',
'Elias',
'Jaxson',
'Greyson',
'Jose',
'Ezekiel',
'Carson',
'Evan',
'Maverick',
'Bryson',
'Jace',
'Cooper',
'Xavier',
'Parker',
'Roman',
'Jason',
'Santiago',
'Chase',
'Sawyer',
'Gavin',
'Leonardo',
'Kayden',
'Ayden',
'Jameson',
'Kevin',
'Bentley',
'Zachary',
'Everett',
'Axel',
'Tyler',
'Micah',
'Vincent',
'Weston',
'Miles',
'Wesley',
'Nathaniel',
'Harrison',
'Brandon',
'Cole',
'Declan',
'Luis',
'Braxton',
'Damian',
'Silas',
'Tristan',
'Ryder',
'Bennett',
'George',
'Emmett',
'Justin',
'Kai',
'Max',
'Diego',
'Luca',
'Ryker',
'Carlos',
'Maxwell',
'Kingston',
'Ivan',
'Maddox',
'Juan',
'Ashton',
'Jayce',
'Rowan',
'Kaiden',
'Giovanni',
'Eric',
'Jesus',
'Calvin',
'Abel',
'King',
'Camden',
'Amir',
'Blake',
'Alex',
'Brody',
'Malachi',
'Emmanuel',
'Jonah',
'Beau',
'Jude',
'Antonio',
'Alan',
'Elliott',
'Elliot',
'Waylon',
'Xander',
'Timothy',
'Victor',
'Bryce',
'Finn',
'Brantley',
'Edward',
'Abraham',
'Patrick',
'Grant',
'Karter',
'Hayden',
'Richard',
'Miguel',
'Joel',
'Gael',
'Tucker',
'Rhett',
'Avery',
'Steven',
'Graham',
'Kaleb',
'Jasper',
'Jesse',
'Matteo',
'Dean',
'Zayden',
'Preston',
'August',
'Oscar',
'Jeremy',
'Alejandro',
'Marcus',
'Dawson',
'Lorenzo',
'Messiah',
'Zion',
'Maximus',
'River',
'Zane',
'Mark',
'Brooks',
'Nicolas',
'Paxton',
'Judah',
'Emiliano',
'Kaden',
'Bryan',
'Kyle',
'Myles',
'Peter',
'Charlie',
'Kyrie',
'Thiago',
'Brian',
'Kenneth',
'Andres',
'Lukas',
'Aidan',
'Jax',
'Caden',
'Milo',
'Paul',
'Beckett',
'Brady',
'Colin',
'Omar',
'Bradley',
'Javier',
'Knox',
'Jaden',
'Barrett',
'Israel',
'Matias',
'Jorge',
'Zander',
'Derek',
'Josue',
'Cayden',
'Holden',
'Griffin',
'Arthur',
'Leon',
'Felix',
'Remington',
'Jake',
'Killian',
'Clayton',
'Sean',
'Adriel',
'Riley',
'Archer',
'Legend',
'Erick',
'Enzo',
'Corbin',
'Francisco',
'Dallas',
'Emilio',
'Gunner',
'Simon',
'Andre',
'Walter',
'Damien',
'Chance',
'Phoenix',
'Colt',
'Tanner',
'Stephen',
'Kameron',
'Tobias',
'Manuel',
'Amari',
'Emerson',
'Louis',
'Cody',
'Finley',
'Iker',
'Martin',
'Rafael',
'Nash',
'Beckham',
'Cash',
'Karson',
'Rylan',
'Reid',
'Theo',
'Ace',
'Eduardo',
'Spencer',
'Raymond',
'Maximiliano',
'Anderson',
'Ronan',
'Lane',
'Cristian',
'Titus',
'Travis',
'Jett',
'Ricardo',
'Bodhi',
'Gideon',
'Jaiden',
'Fernando',
'Mario',
'Conor',
'Keegan',
'Ali',
'Cesar',
'Ellis',
'Jayceon',
'Walker',
'Cohen',
'Arlo',
'Hector',
'Dante',
'Kyler',
'Garrett',
'Donovan',
'Seth',
'Jeffrey',
'Tyson',
'Jase',
'Desmond',
'Caiden',
'Gage',
'Atlas',
'Major',
'Devin',
'Edwin',
'Angelo',
'Orion',
'Conner',
'Julius',
'Marco',
'Jensen',
'Daxton',
'Peyton',
'Zayn',
'Collin',
'Jaylen',
'Dakota',
'Prince',
'Johnny',
'Kayson',
'Cruz',
'Hendrix',
'Atticus',
'Troy',
'Kane',
'Edgar',
'Sergio',
'Kash',
'Marshall',
'Johnathan',
'Romeo',
'Shane',
'Warren',
'Joaquin',
'Wade',
'Leonel',
'Trevor',
'Dominick',
'Muhammad',
'Erik',
'Odin',
'Quinn',
'Jaxton',
'Dalton',
'Nehemiah',
'Frank',
'Grady',
'Gregory',
'Andy',
'Solomon',
'Malik',
'Rory',
'Clark',
'Reed',
'Harvey',
'Zayne',
'Jay',
'Jared',
'Noel',
'Shawn',
'Fabian',
'Ibrahim',
'Adonis',
'Ismael',
'Pedro',
'Leland',
'Malakai',
'Malcolm',
'Alexis',
'Kason',
'Porter',
'Sullivan',
'Raiden',
'Allen',
'Ari',
'Russell',
'Princeton',
'Winston',
'Kendrick',
'Roberto',
'Lennox',
'Hayes',
'Finnegan',
'Nasir',
'Kade',
'Nico',
'Emanuel',
'Landen',
'Moises',
'Ruben',
'Hugo',
'Abram',
'Adan',
'Khalil',
'Zaiden',
'Augustus',
'Marcos',
'Philip',
'Phillip',
'Cyrus',
'Esteban',
'Braylen',
'Albert',
'Bruce',
'Kamden',
'Lawson',
'Jamison',
'Sterling',
'Damon',
'Gunnar',
'Kyson',
'Luka',
'Franklin',
'Ezequiel',
'Pablo',
'Derrick',
'Zachariah',
'Cade',
'Jonas',
'Dexter',
'Kolton',
'Remy',
'Hank',
'Tate',
'Trenton',
'Kian',
'Drew',
'Mohamed',
'Dax',
'Rocco',
'Bowen',
'Mathias',
'Ronald',
'Francis',
'Matthias',
'Milan',
'Maximilian',
'Royce',
'Skyler',
'Corey',
'Kasen',
'Drake',
'Gerardo',
'Jayson',
'Sage',
'Braylon',
'Benson',
'Moses',
'Alijah',
'Rhys',
'Otto',
'Oakley',
'Armando',
'Jaime',
'Nixon',
'Saul',
'Scott',
'Brycen',
'Ariel',
'Enrique',
'Donald',
'Chandler',
'Asa',
'Eden',
'Davis',
'Keith',
'Frederick',
'Rowen',
'Lawrence',
'Leonidas',
'Aden',
'Julio',
'Darius',
'Johan',
'Deacon',
'Cason',
'Danny',
'Nikolai',
'Taylor',
'Alec',
'Royal',
'Armani',
'Kieran',
'Luciano',
'Omari',
'Rodrigo',
'Arjun',
'Ahmed',
'Brendan',
'Cullen',
'Raul',
'Raphael',
'Ronin',
'Brock',
'Pierce',
'Alonzo',
'Casey',
'Dillon',
'Uriel',
'Dustin',
'Gianni',
'Roland',
'Landyn',
'Kobe',
'Dorian',
'Emmitt',
'Ryland',
'Apollo',
'Aarav',
'Roy',
'Duke',
'Quentin',
'Sam',
'Lewis',
'Tony',
'Uriah',
'Dennis',
'Moshe',
'Isaias',
'Braden',
'Quinton',
'Cannon',
'Ayaan',
'Mathew',
'Kellan',
'Niko',
'Edison',
'Izaiah',
'Jerry',
'Gustavo',
'Jamari',
'Marvin',
'Mauricio',
'Ahmad',
'Mohammad',
'Justice',
'Trey',
'Elian',
'Mohammed',
'Sincere',
'Yusuf',
'Arturo',
'Callen',
'Rayan',
'Keaton',
'Wilder',
'Mekhi',
'Memphis',
'Cayson',
'Conrad',
'Kaison',
'Kyree',
'Soren',
'Colby',
'Bryant',
'Lucian',
'Alfredo',
'Cassius',
'Marcelo',
'Nikolas',
'Brennan',
'Darren',
'Jasiah',
'Jimmy',
'Lionel',
'Reece',
'Ty',
'Chris',
'Forrest',
'Korbin',
'Tatum',
'Jalen',
'Santino',
'Case',
'Leonard',
'Alvin',
'Issac',
'Bo',
'Quincy',
'Mack',
'Samson',
'Rex',
'Alberto',
'Callum',
'Curtis',
'Hezekiah',
'Finnley',
'Briggs',
'Kamari',
'Zeke',
'Raylan',
'Neil',
'Titan',
'Julien',
'Kellen',
'Devon',
'Kylan',
'Roger',
'Axton',
'Carl',
'Douglas',
'Larry',
'Crosby',
'Fletcher',
'Makai',
'Nelson',
'Hamza',
'Lance',
'Alden',
'Gary',
'Wilson',
'Alessandro',
'Ares',
'Kashton',
'Bruno',
'Jakob',
'Stetson',
'Zain',
'Cairo',
'Nathanael',
'Byron',
'Harry',
'Harley',
'Mitchell',
'Maurice',
'Orlando',
'Kingsley',
'Kaysen',
'Sylas',
'Trent',
'Ramon',
'Boston',
'Lucca',
'Noe',
'Jagger',
'Reyansh',
'Vihaan',
'Randy',
'Thaddeus',
'Lennon',
'Kannon',
'Kohen',
'Tristen',
'Valentino',
'Maxton',
'Salvador',
'Abdiel',
'Langston',
'Rohan',
'Kristopher',
'Yosef',
'Rayden',
'Lee',
'Callan',
'Tripp',
'Deandre',
'Joe',
'Morgan',
'Dariel',
'Colten',
'Reese',
'Jedidiah',
'Ricky',
'Bronson',
'Terry',
'Eddie',
'Jefferson',
'Lachlan',
'Layne',
'Clay',
'Madden',
'Jamir',
'Tomas',
'Kareem',
'Stanley',
'Brayan',
'Amos',
'Kase',
'Kristian',
'Clyde',
'Ernesto',
'Tommy',
'Casen',
'Ford',
'Crew',
'Braydon',
'Brecken',
'Hassan',
'Axl',
'Boone',
'Leandro',
'Samir',
'Jaziel',
'Magnus',
'Abdullah',
'Yousef',
'Branson',
'Jadiel',
'Jaxen',
'Layton',
'Franco',
'Ben',
'Grey',
'Kelvin',
'Chaim',
'Demetrius',
'Blaine',
'Ridge',
'Colson',
'Melvin',
'Anakin',
'Aryan',
'Lochlan',
'Jon',
'Canaan',
'Dash',
'Zechariah',
'Alonso',
'Otis',
'Zaire',
'Marcel',
'Brett',
'Stefan',
'Aldo',
'Jeffery',
'Baylor',
'Talon',
'Dominik',
'Flynn',
'Carmelo',
'Dane',
'Jamal',
'Kole',
'Enoch',
'Graysen',
'Kye',
'Vicente',
'Fisher',
'Ray',
'Fox',
'Jamie',
'Rey',
'Zaid',
'Allan',
'Emery',
'Gannon',
'Joziah',
'Rodney',
'Juelz',
'Sonny',
'Terrance',
'Zyaire',
'Augustine',
'Cory',
'Felipe',
'Aron',
'Jacoby',
'Harlan',
'Marc',
'Bobby',
'Joey',
'Anson',
'Huxley',
'Marlon',
'Anders',
'Guillermo',
'Payton',
'Castiel',
'Damari',
'Shepherd',
'Azariah',
'Harold',
'Harper',
'Henrik',
'Houston',
'Kairo',
'Willie',
'Elisha',
'Ameer',
'Emory',
'Skylar',
'Sutton',
'Alfonso',
'Brentley',
'Toby',
'Blaze',
'Eugene',
'Shiloh',
'Wayne',
'Darian',
'Gordon',
'London',
'Bodie',
'Jordy',
'Jermaine',
'Denver',
'Gerald',
'Merrick',
'Musa',
'Vincenzo',
'Kody',
'Yahir',
'Brodie',
'Trace',
'Darwin',
'Tadeo',
'Bentlee',
'Billy',
'Hugh',
'Reginald',
'Vance',
'Westin',
'Cain',
'Arian',
'Dayton',
'Javion',
'Terrence',
'Brysen',
'Jaxxon',
'Thatcher',
'Landry',
'Rene',
'Westley',
'Miller',
'Alvaro',
'Cristiano',
'Eliseo',
'Ephraim',
'Adrien',
'Jerome',
'Khalid',
'Aydin',
'Mayson',
'Alfred',
'Duncan',
'Junior',
'Kendall',
'Zavier',
'Koda',
'Maison',
'Caspian',
'Maxim',
'Kace',
'Zackary',
'Rudy',
'Coleman',
'Keagan',
'Kolten',
'Maximo',
'Dario',
'Davion',
'Kalel',
'Briar',
'Jairo',
'Misael',
'Rogelio',
'Terrell',
'Heath',
'Micheal',
'Wesson',
'Aaden',
'Brixton',
'Draven',
'Xzavier',
'Darrell',
'Keanu',
'Ronnie',
'Konnor',
'Will',
'Dangelo',
'Frankie',
'Kamryn',
'Salvatore',
'Santana',
'Shaun',
'Coen',
'Leighton',
'Mustafa',
'Reuben',
'Ayan',
'Blaise',
'Dimitri',
'Keenan',
'Van',
'Achilles',
'Channing',
'Ishaan',
'Wells',
'Benton',
'Lamar',
'Nova',
'Yahya',
'Dilan',
'Gibson',
'Camdyn',
'Ulises',
'Alexzander',
'Valentin',
'Shepard',
'Alistair',
'Eason',
'Kaiser',
'Leroy',
'Zayd',
'Camilo',
'Markus',
'Foster',
'Davian',
'Dwayne',
'Jabari',
'Judson',
'Koa',
'Yehuda',
'Lyric',
'Tristian',
'Agustin',
'Bridger',
'Vivaan',
'Brayson',
'Emmet',
'Marley',
'Mike',
'Nickolas',
'Kenny',
'Leif',
'Bjorn',
'Ignacio',
'Rocky',
'Chad',
'Gatlin',
'Greysen',
'Kyng',
'Randall',
'Reign',
'Vaughn',
'Jessie',
'Louie',
'Shmuel',
'Zahir',
'Ernest',
'Javon',
'Khari',
'Reagan',
'Avi',
'Ira',
'Ledger',
'Simeon',
'Yadiel',
'Maddux',
'Seamus',
'Jad',
'Jeremias',
'Kylen',
'Rashad',
'Santos',
'Cedric',
'Craig',
'Dominique',
'Gianluca',
'Jovanni',
'Bishop',
'Brenden',
'Anton',
'Camron',
'Giancarlo',
'Lyle',
'Alaric',
'Decker',
'Eliezer',
'Ramiro',
'Yisroel',
'Howard',
'Jaxx'
}

SetPlayerSkin.FemaleNames = {
'Emma',
'Olivia',
'Ava',
'Isabella',
'Sophia',
'Mia',
'Charlotte',
'Amelia',
'Evelyn',
'Abigail',
'Harper',
'Emily',
'Elizabeth',
'Avery',
'Sofia',
'Ella',
'Madison',
'Scarlett',
'Victoria',
'Aria',
'Grace',
'Chloe',
'Camila',
'Penelope',
'Riley',
'Layla',
'Lillian',
'Nora',
'Zoey',
'Mila',
'Aubrey',
'Hannah',
'Lily',
'Addison',
'Eleanor',
'Natalie',
'Luna',
'Savannah',
'Brooklyn',
'Leah',
'Zoe',
'Stella',
'Hazel',
'Ellie',
'Paisley',
'Audrey',
'Skylar',
'Violet',
'Claire',
'Bella',
'Aurora',
'Lucy',
'Anna',
'Samantha',
'Caroline',
'Genesis',
'Aaliyah',
'Kennedy',
'Kinsley',
'Allison',
'Maya',
'Sarah',
'Madelyn',
'Adeline',
'Alexa',
'Ariana',
'Elena',
'Gabriella',
'Naomi',
'Alice',
'Sadie',
'Hailey',
'Eva',
'Emilia',
'Autumn',
'Quinn',
'Nevaeh',
'Piper',
'Ruby',
'Serenity',
'Willow',
'Everly',
'Cora',
'Kaylee',
'Lydia',
'Aubree',
'Arianna',
'Eliana',
'Peyton',
'Melanie',
'Gianna',
'Isabelle',
'Julia',
'Valentina',
'Nova',
'Clara',
'Vivian',
'Reagan',
'Mackenzie',
'Madeline',
'Brielle',
'Delilah',
'Isla',
'Rylee',
'Katherine',
'Sophie',
'Josephine',
'Ivy',
'Liliana',
'Jade',
'Maria',
'Taylor',
'Hadley',
'Kylie',
'Emery',
'Adalynn',
'Natalia',
'Annabelle',
'Faith',
'Alexandra',
'Ximena',
'Ashley',
'Brianna',
'Raelynn',
'Bailey',
'Mary',
'Athena',
'Andrea',
'Leilani',
'Jasmine',
'Lyla',
'Margaret',
'Alyssa',
'Adalyn',
'Arya',
'Norah',
'Khloe',
'Kayla',
'Eden',
'Eliza',
'Rose',
'Ariel',
'Melody',
'Alexis',
'Isabel',
'Sydney',
'Juliana',
'Lauren',
'Iris',
'Emerson',
'London',
'Morgan',
'Lilly',
'Charlie',
'Aliyah',
'Valeria',
'Arabella',
'Sara',
'Finley',
'Trinity',
'Ryleigh',
'Jordyn',
'Jocelyn',
'Kimberly',
'Esther',
'Molly',
'Valerie',
'Cecilia',
'Anastasia',
'Daisy',
'Reese',
'Laila',
'Mya',
'Amy',
'Teagan',
'Amaya',
'Elise',
'Harmony',
'Paige',
'Adaline',
'Fiona',
'Alaina',
'Nicole',
'Genevieve',
'Lucia',
'Alina',
'Mckenzie',
'Callie',
'Payton',
'Eloise',
'Brooke',
'Londyn',
'Mariah',
'Julianna',
'Rachel',
'Daniela',
'Gracie',
'Catherine',
'Angelina',
'Presley',
'Josie',
'Harley',
'Adelyn',
'Vanessa',
'Makayla',
'Parker',
'Juliette',
'Amara',
'Marley',
'Lila',
'Ana',
'Rowan',
'Alana',
'Michelle',
'Malia',
'Rebecca',
'Brooklynn',
'Brynlee',
'Summer',
'Sloane',
'Leila',
'Sienna',
'Adriana',
'Sawyer',
'Kendall',
'Juliet',
'Destiny',
'Alayna',
'Elliana',
'Diana',
'Hayden',
'Ayla',
'Dakota',
'Angela',
'Noelle',
'Rosalie',
'Joanna',
'Jayla',
'Alivia',
'Lola',
'Emersyn',
'Georgia',
'Selena',
'June',
'Daleyza',
'Tessa',
'Maggie',
'Jessica',
'Remi',
'Delaney',
'Camille',
'Vivienne',
'Hope',
'Mckenna',
'Gemma',
'Olive',
'Alexandria',
'Blakely',
'Izabella',
'Catalina',
'Raegan',
'Journee',
'Gabrielle',
'Lucille',
'Ruth',
'Amiyah',
'Evangeline',
'Blake',
'Thea',
'Amina',
'Giselle',
'Lilah',
'Melissa',
'River',
'Kate',
'Adelaide',
'Charlee',
'Vera',
'Leia',
'Gabriela',
'Zara',
'Jane',
'Journey',
'Elaina',
'Miriam',
'Briella',
'Stephanie',
'Cali',
'Ember',
'Lilliana',
'Aniyah',
'Logan',
'Kamila',
'Brynn',
'Ariella',
'Makenzie',
'Annie',
'Mariana',
'Kali',
'Haven',
'Elsie',
'Nyla',
'Paris',
'Lena',
'Freya',
'Adelynn',
'Lyric',
'Camilla',
'Sage',
'Jennifer',
'Paislee',
'Talia',
'Alessandra',
'Juniper',
'Fatima',
'Raelyn',
'Amira',
'Arielle',
'Phoebe',
'Kinley',
'Ada',
'Nina',
'Ariah',
'Samara',
'Myla',
'Brinley',
'Cassidy',
'Maci',
'Aspen',
'Allie',
'Keira',
'Kaia',
'Makenna',
'Amanda',
'Heaven',
'Joy',
'Lia',
'Madilyn',
'Gracelyn',
'Laura',
'Evelynn',
'Lexi',
'Haley',
'Miranda',
'Kaitlyn',
'Daniella',
'Felicity',
'Jacqueline',
'Evie',
'Angel',
'Danielle',
'Ainsley',
'Dylan',
'Kiara',
'Millie',
'Jordan',
'Maddison',
'Rylie',
'Alicia',
'Maeve',
'Margot',
'Kylee',
'Phoenix',
'Heidi',
'Zuri',
'Alondra',
'Lana',
'Madeleine',
'Gracelynn',
'Kenzie',
'Miracle',
'Shelby',
'Elle',
'Adrianna',
'Bianca',
'Addilyn',
'Kira',
'Veronica',
'Gwendolyn',
'Esmeralda',
'Chelsea',
'Alison',
'Skyler',
'Magnolia',
'Daphne',
'Jenna',
'Everleigh',
'Kyla',
'Braelynn',
'Harlow',
'Annalise',
'Mikayla',
'Dahlia',
'Maliyah',
'Averie',
'Scarlet',
'Kayleigh',
'Luciana',
'Kelsey',
'Nadia',
'Amber',
'Gia',
'Kamryn',
'Yaretzi',
'Carmen',
'Jimena',
'Erin',
'Christina',
'Katie',
'Ryan',
'Viviana',
'Alexia',
'Anaya',
'Serena',
'Katelyn',
'Ophelia',
'Regina',
'Helen',
'Remington',
'Camryn',
'Cadence',
'Royalty',
'Amari',
'Kathryn',
'Skye',
'Emely',
'Jada',
'Ariyah',
'Aylin',
'Saylor',
'Kendra',
'Cheyenne',
'Fernanda',
'Sabrina',
'Francesca',
'Eve',
'Mckinley',
'Frances',
'Sarai',
'Carolina',
'Kennedi',
'Nylah',
'Tatum',
'Alani',
'Lennon',
'Raven',
'Zariah',
'Leslie',
'Winter',
'Abby',
'Mabel',
'Sierra',
'April',
'Willa',
'Carly',
'Jolene',
'Rosemary',
'Aviana',
'Madelynn',
'Selah',
'Renata',
'Lorelei',
'Briana',
'Celeste',
'Wren',
'Charleigh',
'Leighton',
'Annabella',
'Jayleen',
'Braelyn',
'Ashlyn',
'Jazlyn',
'Mira',
'Oakley',
'Malaysia',
'Edith',
'Avianna',
'Maryam',
'Emmalyn',
'Hattie',
'Kensley',
'Macie',
'Bristol',
'Marlee',
'Demi',
'Cataleya',
'Maia',
'Sylvia',
'Itzel',
'Allyson',
'Lilith',
'Melany',
'Kaydence',
'Holly',
'Nayeli',
'Meredith',
'Nia',
'Liana',
'Megan',
'Justice',
'Bethany',
'Alejandra',
'Janelle',
'Elisa',
'Adelina',
'Ashlynn',
'Elianna',
'Aleah',
'Myra',
'Lainey',
'Blair',
'Kassidy',
'Charley',
'Virginia',
'Kara',
'Helena',
'Sasha',
'Julie',
'Michaela',
'Carter',
'Matilda',
'Kehlani',
'Henley',
'Maisie',
'Hallie',
'Jazmin',
'Priscilla',
'Marilyn',
'Cecelia',
'Danna',
'Colette',
'Baylee',
'Elliott',
'Ivanna',
'Cameron',
'Celine',
'Alayah',
'Hanna',
'Imani',
'Angelica',
'Emelia',
'Kalani',
'Alanna',
'Lorelai',
'Macy',
'Karina',
'Addyson',
'Aleena',
'Aisha',
'Johanna',
'Mallory',
'Leona',
'Mariam',
'Kynlee',
'Madilynn',
'Karen',
'Karla',
'Skyla',
'Beatrice',
'Dayana',
'Gloria',
'Milani',
'Savanna',
'Karsyn',
'Rory',
'Giuliana',
'Lauryn',
'Liberty',
'Galilea',
'Aubrie',
'Charli',
'Kyleigh',
'Brylee',
'Jillian',
'Anne',
'Haylee',
'Dallas',
'Azalea',
'Jayda',
'Tiffany',
'Avah',
'Shiloh',
'Bailee',
'Jazmine',
'Esme',
'Coraline',
'Madisyn',
'Elaine',
'Lilian',
'Kyra',
'Kaliyah',
'Kora',
'Octavia',
'Irene',
'Kelly',
'Lacey',
'Laurel',
'Adley',
'Anika',
'Janiyah',
'Dorothy',
'Sutton',
'Julieta',
'Kimber',
'Remy',
'Cassandra',
'Rebekah',
'Collins',
'Elliot',
'Emmy',
'Sloan',
'Hayley',
'Amalia',
'Jemma',
'Jamie',
'Melina',
'Leyla',
'Jaylah',
'Anahi',
'Jaliyah',
'Kailani',
'Harlee',
'Wynter',
'Saige',
'Alessia',
'Monica',
'Anya',
'Antonella',
'Emberly',
'Khaleesi',
'Ivory',
'Greta',
'Maren',
'Alena',
'Emory',
'Alaia',
'Cynthia',
'Addisyn',
'Alia',
'Lylah',
'Angie',
'Ariya',
'Alma',
'Crystal',
'Jayde',
'Aileen',
'Kinslee',
'Siena',
'Zelda',
'Katalina',
'Marie',
'Pearl',
'Reyna',
'Mae',
'Zahra',
'Kailey',
'Jessie',
'Tiana',
'Amirah',
'Madalyn',
'Alaya',
'Lilyana',
'Julissa',
'Armani',
'Lennox',
'Lillie',
'Jolie',
'Laney',
'Roselyn',
'Mara',
'Joelle',
'Rosa',
'Kaylani',
'Bridget',
'Liv',
'Oaklyn',
'Aurelia',
'Clarissa',
'Elyse',
'Marissa',
'Monroe',
'Kori',
'Elsa',
'Rosie',
'Amelie',
'Aitana',
'Aliza',
'Eileen',
'Poppy',
'Emmie',
'Braylee',
'Milana',
'Addilynn',
'Royal',
'Chaya',
'Frida',
'Bonnie',
'Amora',
'Stevie',
'Tatiana',
'Malaya',
'Mina',
'Emerie',
'Reign',
'Zaylee',
'Annika',
'Kenia',
'Linda',
'Kenna',
'Faye',
'Reina',
'Brittany',
'Marina',
'Astrid',
'Kadence',
'Mikaela',
'Jaelyn',
'Briar',
'Kaylie',
'Teresa',
'Bria',
'Hadassah',
'Lilianna',
'Guadalupe',
'Rayna',
'Chanel',
'Lyra',
'Noa',
'Zariyah',
'Laylah',
'Aubrielle',
'Aniya',
'Livia',
'Ellen',
'Meadow',
'Amiya',
'Ellis',
'Elora',
'Milan',
'Hunter',
'Princess',
'Leanna',
'Nathalie',
'Clementine',
'Nola',
'Tenley',
'Simone',
'Lina',
'Marianna',
'Martha',
'Sariah',
'Louisa',
'Noemi',
'Emmeline',
'Kenley',
'Belen',
'Erika',
'Myah',
'Lara',
'Amani',
'Ansley',
'Everlee',
'Maleah',
'Salma',
'Jaelynn',
'Kiera',
'Dulce',
'Nala',
'Natasha',
'Averi',
'Mercy',
'Penny',
'Ariadne',
'Deborah',
'Elisabeth',
'Zaria',
'Hana',
'Kairi',
'Yareli',
'Raina',
'Ryann',
'Lexie',
'Thalia',
'Karter',
'Annabel',
'Christine',
'Estella',
'Keyla',
'Adele',
'Aya',
'Estelle',
'Landry',
'Tori',
'Perla',
'Lailah',
'Miah',
'Rylan',
'Angelique',
'Avalynn',
'Romina',
'Ari',
'Jaycee',
'Jaylene',
'Kai',
'Louise',
'Mavis',
'Scarlette',
'Belle',
'Lea',
'Nalani',
'Rivka',
'Ayleen',
'Calliope',
'Dalary',
'Zaniyah',
'Kaelyn',
'Sky',
'Jewel',
'Joselyn',
'Madalynn',
'Paola',
'Giovanna',
'Isabela',
'Karlee',
'Aubriella',
'Azariah',
'Tinley',
'Dream',
'Claudia',
'Corinne',
'Erica',
'Milena',
'Aliana',
'Kallie',
'Alyson',
'Joyce',
'Tinsley',
'Whitney',
'Emilee',
'Paisleigh',
'Carolyn',
'Jaylee',
'Zoie',
'Frankie',
'Andi',
'Judith',
'Paula',
'Xiomara',
'Aiyana',
'Amia',
'Analia',
'Audrina',
'Hadlee',
'Rayne',
'Amayah',
'Cara',
'Celia',
'Lyanna',
'Opal',
'Amaris',
'Clare',
'Gwen',
'Giana',
'Veda',
'Alisha',
'Davina',
'Rhea',
'Sariyah',
'Noor',
'Danica',
'Kathleen',
'Lillianna',
'Lindsey',
'Maxine',
'Paulina',
'Hailee',
'Harleigh',
'Nancy',
'Jessa',
'Raquel',
'Raylee',
'Zainab',
'Chana',
'Lisa',
'Heavenly',
'Oaklynn',
'Aminah',
'Emmalynn',
'Patricia',
'India',
'Janessa',
'Paloma',
'Ramona',
'Sandra',
'Abril',
'Emmaline',
'Itzayana',
'Kassandra',
'Vienna',
'Marleigh',
'Kailyn',
'Novalee',
'Rosalyn',
'Hadleigh',
'Luella',
'Taliyah',
'Avalyn',
'Barbara',
'Iliana',
'Jana',
'Meilani',
'Aadhya',
'Alannah',
'Blaire',
'Brenda',
'Casey',
'Selene',
'Lizbeth',
'Adrienne',
'Annalee',
'Malani',
'Aliya',
'Miley',
'Nataly',
'Bexley',
'Joslyn',
'Maliah',
'Zion',
'Breanna',
'Melania',
'Estrella',
'Ingrid',
'Jayden',
'Kaya',
'Kaylin',
'Harmoni',
'Arely',
'Jazlynn',
'Kiana',
'Dana',
'Mylah',
'Oaklee',
'Ailani',
'Kailee',
'Legacy',
'Marjorie',
'Paityn',
'Courtney',
'Ellianna',
'Jurnee',
'Karlie',
'Evalyn',
'Holland',
'Kenya',
'Magdalena',
'Carla',
'Halle',
'Aryanna',
'Kaiya',
'Kimora',
'Naya',
'Saoirse',
'Susan',
'Desiree',
'Ensley',
'Renee',
'Esperanza',
'Treasure',
'Caylee',
'Ellison',
'Kristina',
'Adilynn',
'Anabelle',
'Egypt',
'Spencer',
'Tegan',
'Aranza',
'Vada',
'Emerald',
'Florence',
'Marlowe',
'Micah',
'Sonia',
'Sunny',
'Tara',
'Riya',
'Yara',
'Alisa',
'Nathalia',
'Yamileth',
'Saanvi',
'Samira',
'Sylvie',
'Brenna',
'Carlee',
'Jenny',
'Miya',
'Monserrat',
'Zendaya',
'Alora'
}

SetPlayerSkin.FamilyNames = {
'SMITH',
'JOHNSON',
'WILLIAMS',
'BROWN',
'JONES',
'GARCIA',
'MILLER',
'DAVIS',
'RODRIGUEZ',
'MARTINEZ',
'HERNANDEZ',
'LOPEZ',
'GONZALEZ',
'WILSON',
'ANDERSON',
'THOMAS',
'TAYLOR',
'MOORE',
'JACKSON',
'MARTIN',
'LEE',
'PEREZ',
'THOMPSON',
'WHITE',
'HARRIS',
'SANCHEZ',
'CLARK',
'RAMIREZ',
'LEWIS',
'ROBINSON',
'WALKER',
'YOUNG',
'ALLEN',
'KING',
'WRIGHT',
'SCOTT',
'TORRES',
'NGUYEN',
'HILL',
'FLORES',
'GREEN',
'ADAMS',
'NELSON',
'BAKER',
'HALL',
'RIVERA',
'CAMPBELL',
'MITCHELL',
'CARTER',
'ROBERTS',
'GOMEZ',
'PHILLIPS',
'EVANS',
'TURNER',
'DIAZ',
'PARKER',
'CRUZ',
'EDWARDS',
'COLLINS',
'REYES',
'STEWART',
'MORRIS',
'MORALES',
'MURPHY',
'COOK',
'ROGERS',
'GUTIERREZ',
'ORTIZ',
'MORGAN',
'COOPER',
'PETERSON',
'BAILEY',
'REED',
'KELLY',
'HOWARD',
'RAMOS',
'KIM',
'COX',
'WARD',
'RICHARDSON',
'WATSON',
'BROOKS',
'CHAVEZ',
'WOOD',
'JAMES',
'BENNETT',
'GRAY',
'MENDOZA',
'RUIZ',
'HUGHES',
'PRICE',
'ALVAREZ',
'CASTILLO',
'SANDERS',
'PATEL',
'MYERS',
'LONG',
'ROSS',
'FOSTER',
'JIMENEZ',
'POWELL',
'JENKINS',
'PERRY',
'RUSSELL',
'SULLIVAN',
'BELL',
'COLEMAN',
'BUTLER',
'HENDERSON',
'BARNES',
'GONZALES',
'FISHER',
'VASQUEZ',
'SIMMONS',
'ROMERO',
'JORDAN',
'PATTERSON',
'ALEXANDER',
'HAMILTON',
'GRAHAM',
'REYNOLDS',
'GRIFFIN',
'WALLACE',
'MORENO',
'WEST',
'COLE',
'HAYES',
'BRYANT',
'HERRERA',
'GIBSON',
'ELLIS',
'TRAN',
'MEDINA',
'AGUILAR',
'STEVENS',
'MURRAY',
'FORD',
'CASTRO',
'MARSHALL',
'OWENS',
'HARRISON',
'FERNANDEZ',
'MCDONALD',
'WOODS',
'WASHINGTON',
'KENNEDY',
'WELLS',
'VARGAS',
'HENRY',
'CHEN',
'FREEMAN',
'WEBB',
'TUCKER',
'GUZMAN',
'BURNS',
'CRAWFORD',
'OLSON',
'SIMPSON',
'PORTER',
'HUNTER',
'GORDON',
'MENDEZ',
'SILVA',
'SHAW',
'SNYDER',
'MASON',
'DIXON',
'MUNOZ',
'HUNT',
'HICKS',
'HOLMES',
'PALMER',
'WAGNER',
'BLACK',
'ROBERTSON',
'BOYD',
'ROSE',
'STONE',
'SALAZAR',
'FOX',
'WARREN',
'MILLS',
'MEYER',
'RICE',
'SCHMIDT',
'GARZA',
'DANIELS',
'FERGUSON',
'NICHOLS',
'STEPHENS',
'SOTO',
'WEAVER',
'RYAN',
'GARDNER',
'PAYNE',
'GRANT',
'DUNN',
'KELLEY',
'SPENCER',
'HAWKINS',
'ARNOLD',
'PIERCE',
'VAZQUEZ',
'HANSEN',
'PETERS',
'SANTOS',
'HART',
'BRADLEY',
'KNIGHT',
'ELLIOTT',
'CUNNINGHAM',
'DUNCAN',
'ARMSTRONG',
'HUDSON',
'CARROLL',
'LANE',
'RILEY',
'ANDREWS',
'ALVARADO',
'RAY',
'DELGADO',
'BERRY',
'PERKINS',
'HOFFMAN',
'JOHNSTON',
'MATTHEWS',
'PENA',
'RICHARDS',
'CONTRERAS',
'WILLIS',
'CARPENTER',
'LAWRENCE',
'SANDOVAL',
'GUERRERO',
'GEORGE',
'CHAPMAN',
'RIOS',
'ESTRADA',
'ORTEGA',
'WATKINS',
'GREENE',
'NUNEZ',
'WHEELER',
'VALDEZ',
'HARPER',
'BURKE',
'LARSON',
'SANTIAGO',
'MALDONADO',
'MORRISON',
'FRANKLIN',
'CARLSON',
'AUSTIN',
'DOMINGUEZ',
'CARR',
'LAWSON',
'JACOBS',
'OBRIEN',
'LYNCH',
'SINGH',
'VEGA',
'BISHOP',
'MONTGOMERY',
'OLIVER',
'JENSEN',
'HARVEY',
'WILLIAMSON',
'GILBERT',
'DEAN',
'SIMS',
'ESPINOZA',
'HOWELL',
'LI',
'WONG',
'REID',
'HANSON',
'LE',
'MCCOY',
'GARRETT',
'BURTON',
'FULLER',
'WANG',
'WEBER',
'WELCH',
'ROJAS',
'LUCAS',
'MARQUEZ',
'FIELDS',
'PARK',
'YANG',
'LITTLE',
'BANKS',
'PADILLA',
'DAY',
'WALSH',
'BOWMAN',
'SCHULTZ',
'LUNA',
'FOWLER',
'MEJIA',
'DAVIDSON',
'ACOSTA',
'BREWER',
'MAY',
'HOLLAND',
'JUAREZ',
'NEWMAN',
'PEARSON',
'CURTIS',
'CORTEZ',
'DOUGLAS',
'SCHNEIDER',
'JOSEPH',
'BARRETT',
'NAVARRO',
'FIGUEROA',
'KELLER',
'AVILA',
'WADE',
'MOLINA',
'STANLEY',
'HOPKINS',
'CAMPOS',
'BARNETT',
'BATES',
'CHAMBERS',
'CALDWELL',
'BECK',
'LAMBERT',
'MIRANDA',
'BYRD',
'CRAIG',
'AYALA',
'LOWE',
'FRAZIER',
'POWERS',
'NEAL',
'LEONARD',
'GREGORY',
'CARRILLO',
'SUTTON',
'FLEMING',
'RHODES',
'SHELTON',
'SCHWARTZ',
'NORRIS',
'JENNINGS',
'WATTS',
'DURAN',
'WALTERS',
'COHEN',
'MCDANIEL',
'MORAN',
'PARKS',
'STEELE',
'VAUGHN',
'BECKER',
'HOLT',
'DELEON',
'BARKER',
'TERRY',
'HALE',
'LEON',
'HAIL',
'BENSON',
'HAYNES',
'HORTON',
'MILES',
'LYONS',
'PHAM',
'GRAVES',
'BUSH',
'THORNTON',
'WOLFE',
'WARNER',
'CABRERA',
'MCKINNEY',
'MANN',
'ZIMMERMAN',
'DAWSON',
'LARA',
'FLETCHER',
'PAGE',
'MCCARTHY',
'LOVE',
'ROBLES',
'CERVANTES',
'SOLIS',
'ERICKSON',
'REEVES',
'CHANG',
'KLEIN',
'SALINAS',
'FUENTES',
'BALDWIN',
'DANIEL',
'SIMON',
'VELASQUEZ',
'HARDY',
'HIGGINS',
'AGUIRRE',
'LIN',
'CUMMINGS',
'CHANDLER',
'SHARP',
'BARBER',
'BOWEN',
'OCHOA',
'DENNIS',
'ROBBINS',
'LIU',
'RAMSEY',
'FRANCIS',
'GRIFFITH',
'PAUL',
'BLAIR',
'OCONNOR',
'CARDENAS',
'PACHECO',
'CROSS',
'CALDERON',
'QUINN',
'MOSS',
'SWANSON',
'CHAN',
'RIVAS',
'KHAN',
'RODGERS',
'SERRANO',
'FITZGERALD',
'ROSALES',
'STEVENSON',
'CHRISTENSEN',
'MANNING',
'GILL',
'CURRY',
'MCLAUGHLIN',
'HARMON',
'MCGEE',
'GROSS',
'DOYLE',
'GARNER',
'NEWTON',
'BURGESS',
'REESE',
'WALTON',
'BLAKE',
'TRUJILLO',
'ADKINS',
'BRADY',
'GOODMAN',
'ROMAN',
'WEBSTER',
'GOODWIN',
'FISCHER',
'HUANG',
'POTTER',
'DELACRUZ',
'MONTOYA',
'TODD',
'WU',
'HINES',
'MULLINS',
'CASTANEDA',
'MALONE',
'CANNON',
'TATE',
'MACK',
'SHERMAN',
'HUBBARD',
'HODGES',
'ZHANG',
'GUERRA',
'WOLF',
'VALENCIA',
'FRANCO',
'SAUNDERS',
'ROWE',
'GALLAGHER',
'FARMER',
'HAMMOND',
'HAMPTON',
'TOWNSEND',
'INGRAM',
'WISE',
'GALLEGOS',
'CLARKE',
'BARTON',
'SCHROEDER',
'MAXWELL',
'WATERS',
'LOGAN',
'CAMACHO',
'STRICKLAND',
'NORMAN',
'PERSON',
'COLON',
'PARSONS',
'FRANK',
'HARRINGTON',
'GLOVER',
'OSBORNE',
'BUCHANAN',
'CASEY',
'FLOYD',
'PATTON',
'IBARRA',
'BALL',
'TYLER',
'SUAREZ',
'BOWERS',
'OROZCO',
'SALAS',
'COBB',
'GIBBS',
'ANDRADE',
'BAUER',
'CONNER',
'MOODY',
'ESCOBAR',
'MCGUIRE',
'LLOYD',
'MUELLER',
'HARTMAN',
'FRENCH',
'KRAMER',
'MCBRIDE',
'POPE',
'LINDSEY',
'VELAZQUEZ',
'NORTON',
'MCCORMICK',
'SPARKS',
'FLYNN',
'YATES',
'HOGAN',
'MARSH',
'MACIAS',
'VILLANUEVA',
'ZAMORA',
'PRATT',
'STOKES',
'OWEN',
'BALLARD',
'LANG',
'BROCK',
'VILLARREAL',
'CHARLES',
'DRAKE',
'BARRERA',
'CAIN',
'PATRICK',
'PINEDA',
'BURNETT',
'MERCADO',
'SANTANA',
'SHEPHERD',
'BAUTISTA',
'ALI',
'SHAFFER',
'LAMB',
'TREVINO',
'MCKENZIE',
'HESS',
'BEIL',
'OLSEN',
'COCHRAN',
'MORTON',
'NASH',
'WILKINS',
'PETERSEN',
'BRIGGS',
'SHAH',
'ROTH',
'NICHOLSON',
'HOLLOWAY',
'LOZANO',
'FLOWERS',
'RANGEL',
'HOOVER',
'ARIAS',
'SHORT',
'MORA',
'VALENZUELA',
'BRYAN',
'MEYERS',
'WEISS',
'UNDERWOOD',
'BASS',
'GREER',
'SUMMERS',
'HOUSTON',
'CARSON',
'MORROW',
'CLAYTON',
'WHITAKER',
'DECKER',
'YODER',
'COLLIER',
'ZUNIGA',
'CAREY',
'WILCOX',
'MELENDEZ',
'POOLE',
'ROBERSON',
'LARSEN',
'CONLEY',
'DAVENPORT',
'COPELAND',
'MASSEY',
'LAM',
'HUFF',
'ROCHA',
'CAMERON',
'JEFFERSON',
'HOOD',
'MONROE',
'ANTHONY',
'PITTMAN',
'HUYNH',
'RANDALL',
'SINGLETON',
'KIRK',
'COMBS',
'MATHIS',
'CHRISTIAN',
'SKINNER',
'BRADFORD',
'RICHARD',
'GALVAN',
'WALL',
'BOONE',
'KIRBY',
'WILKINSON',
'BRIDGES',
'BRUCE',
'ATKINSON',
'VELEZ',
'MEZA',
'ROY',
'VINCENT',
'YORK',
'HODGE',
'VILLA',
'ABBOTT',
'ALLISON',
'TAPIA',
'GATES',
'CHASE',
'SOSA',
'SWEENEY',
'FARRELL',
'WYATT',
'DALTON',
'HORN',
'BARRON',
'PHELPS',
'YU',
'DICKERSON',
'HEATH',
'FOLEY',
'ATKINS',
'MATHEWS',
'BONILLA',
'ACEVEDO',
'BENITEZ',
'ZAVALA',
'HENSLEY',
'GLENN',
'CISNEROS',
'HARRELL',
'SHIELDS',
'RUBIO',
'CHOI',
'HUFFMAN',
'BOYER',
'GARRISON',
'ARROYO',
'BOND',
'KANE',
'HANCOCK',
'CALLAHAN',
'DILLON',
'CLINE',
'WIGGINS',
'GRIMES',
'ARELLANO',
'MELTON',
'ONEILL',
'SAVAGE',
'HO',
'BELTRAN',
'PITTS',
'PARRISH',
'PONCE',
'RICH',
'BOOTH',
'KOCH',
'GOLDEN',
'WARE',
'BRENNAN',
'MCDOWELL',
'MARKS',
'CANTU',
'HUMPHREY',
'BAXTER',
'SAWYER',
'CLAY',
'TANNER',
'HUTCHINSON',
'KAUR',
'BERG',
'WILEY',
'GILMORE',
'RUSSO',
'VILLEGAS',
'HOBBS',
'KEITH',
'WILKERSON',
'AHMED',
'BEARD',
'MCCLAIN',
'MONTES',
'MATA',
'ROSARIO',
'VANG',
'WALTER',
'HENSON',
'ONEAL',
'MOSLEY',
'MCCLURE',
'BEASLEY',
'STEPHENSON',
'SNOW',
'HUERTA',
'PRESTON',
'VANCE',
'BARRY',
'JOHNS',
'EATON',
'BLACKWELL',
'DYER',
'PRINCE',
'MACDONALD',
'SOLOMON',
'GUEVARA',
'STAFFORD',
'ENGLISH',
'HURST',
'WOODARD',
'CORTES',
'SHANNON',
'KEMP',
'NOLAN',
'MCCULLOUGH',
'MERRITT',
'MURILLO',
'MOON',
'SALGADO',
'STRONG',
'KLINE',
'CORDOVA',
'BARAJAS',
'ROACH',
'ROSAS',
'WINTERS',
'JACOBSON',
'LESTER',
'KNOX',
'BULLOCK',
'KERR',
'LEACH',
'MEADOWS',
'DAVILA',
'ORR',
'WHITEHEAD',
'PRUITT',
'KENT',
'CONWAY',
'MCKEE',
'BARR',
'DAVID',
'DEJESUS',
'MARIN',
'BERGER',
'MCINTYRE',
'BLANKENSHIP',
'GAINES',
'PALACIOS',
'CUEVAS',
'BARTLETT',
'DURHAM',
'DORSEY',
'MCCALL',
'ODONNELL',
'STEIN',
'BROWNING',
'STOUT',
'LOWERY',
'SLOAN',
'MCLEAN',
'HENDRICKS',
'CALHOUN',
'SEXTON',
'CHUNG',
'GENTRY',
'HULL',
'DUARTE',
'ELLISON',
'NIELSEN',
'GILLESPIE',
'BUCK',
'MIDDLETON',
'SELLERS',
'LEBLANC',
'ESPARZA',
'HARDIN',
'BRADSHAW',
'MCINTOSH',
'HOWE',
'LIVINGSTON',
'FROST',
'GLASS',
'MORSE',
'KNAPP',
'HERMAN',
'STARK',
'BRAVO',
'NOBLE',
'SPEARS',
'WEEKS',
'CORONA',
'FREDERICK',
'BUCKLEY',
'MCFARLAND',
'HEBERT',
'ENRIQUEZ',
'HICKMAN',
'QUINTERO',
'RANDOLPH',
'SCHAEFER',
'WALLS',
'TREJO',
'HOUSE',
'REILLY',
'PENNINGTON',
'MICHAEL',
'CONRAD',
'GILES',
'BENJAMIN',
'CROSBY',
'FITZPATRICK',
'DONOVAN',
'MAYS',
'MAHONEY',
'VALENTINE',
'RAYMOND',
'MEDRANO',
'HAHN',
'MCMILLAN',
'SMALL',
'BENTLEY',
'FELIX',
'PECK',
'LUCERO',
'BOYLE',
'HANNA',
'PACE',
'RUSH',
'HURLEY',
'HARDING',
'MCCONNELL',
'BERNAL',
'NAVA',
'AYERS',
'EVERETT',
'VENTURA',
'AVERY',
'PUGH',
'MAYER',
'BENDER',
'SHEPARD',
'MCMAHON',
'LANDRY',
'CASE',
'SAMPSON',
'MOSES',
'MAGANA',
'BLACKBURN',
'DUNLAP',
'GOULD',
'DUFFY',
'VAUGHAN',
'HERRING',
'MCKAY',
'ESPINOSA',
'RIVERS',
'FARLEY',
'BERNARD',
'ASHLEY',
'FRIEDMAN',
'POTTS',
'TRUONG',
'COSTA',
'CORREA',
'BLEVINS',
'NIXON',
'CLEMENTS',
'FRY',
'DELAROSA',
'BEST',
'BENTON',
'LUGO',
'PORTILLO',
'DOUGHERTY',
'CRANE',
'HALEY',
'PHAN',
'VILLALOBOS',
'BLANCHARD',
'HORNE',
'FINLEY',
'QUINTANA',
'LYNN',
'ESQUIVEL',
'BEAN',
'DODSON',
'MULLEN',
'XIONG',
'HAYDEN',
'CANO',
'LEVY',
'HUBER',
'RICHMOND',
'MOYER',
'LIM',
'FRYE',
'SHEPPARD',
'MCCARTY',
'AVALOS',
'BOOKER',
'WALLER',
'PARRA',
'WOODWARD',
'JARAMILLO',
'KRUEGER',
'RASMUSSEN',
'BRANDT',
'PERALTA',
'DONALDSON',
'STUART',
'FAULKNER',
'MAYNARD',
'GALINDO',
'COFFEY',
'ESTES',
'SANFORD',
'BURCH',
'MADDOX',
'VO',
'OCONNELL',
'VU',
'ANDERSEN',
'SPENCE',
'MCPHERSON',
'CHURCH',
'SCHMITT',
'STANTON',
'LEAL',
'CHERRY',
'COMPTON',
'DUDLEY',
'SIERRA',
'POLLARD',
'ALFARO',
'HESTER',
'PROCTOR',
'LU',
'HINTON',
'NOVAK',
'GOOD',
'MADDEN',
'MCCANN',
'TERRELL',
'JARVIS',
'DICKSON',
'REYNA',
'CANTRELL',
'MAYO',
'BRANCH',
'HENDRIX',
'ROLLINS',
'ROWLAND',
'WHITNEY',
'DUKE',
'ODOM',
'DAUGHERTY',
'TRAVIS',
'TANG',
'ARCHER'
}
SetPlayerSkin.PlayerSkins = {
    SetPlayerSkin(0, "A young black man in a black sleeveless t-shirt and blue jeans", 1),
    SetPlayerSkin(1, "An old white man in a red shirt with black and white plaids, khaki pants and with a red headband", 1),
    SetPlayerSkin(2, "A young white man in a white hoody, blue jeans and with a white hat", 1),
    -- SetPlayerSkin(3, "Andre", 1),                                           ---> not working
    -- SetPlayerSkin(4, "Barry \"Big Bear\" Thorne[Thin]", 1),                 ---> not working
    -- SetPlayerSkin(5, "Barry \"Big Bear\" Thorne[Big]", 1),                  ---> not working
    -- SetPlayerSkin(6, "Emmet", 1),                                           ---> not working
    SetPlayerSkin(7, "A young black man in a blue jeans jacket and beige pants", 1),
    -- SetPlayerSkin(8, "Janitor", 1),                                         ---> not working
    SetPlayerSkin(9, "An old black woman in a brown suit", 2),
    SetPlayerSkin(10, "An old woman in a red shirt with black plaid and a khaki skirt", 2),
    SetPlayerSkin(11, "A young black woman in a black suit without jacket", 2),
    SetPlayerSkin(12, "A young white woman in a black dress", 2),
    SetPlayerSkin(13, "A young black woman in a purple t-shirt, blue jeans and with a beige hat", 2),
    SetPlayerSkin(14, "An old bald black man in a colourful shirt and brown pants", 1),
    SetPlayerSkin(15, "An old bald black man in a white shirt with black plaid and blue jeans", 1),
    SetPlayerSkin(16, "A middle-aged black man in a black shirt and orange vest, black jeans and with a black cap and headphones", 1),
    SetPlayerSkin(17, "A middle-aged black man in a black suit", 1),
    SetPlayerSkin(18, "A young black man in red ang green shorts", 1),
    SetPlayerSkin(19, "A young black man in red pants and with a red head", 1),
    SetPlayerSkin(20, "A young white man in a yellow and black shirt and black pants", 1),
    SetPlayerSkin(21, "A young black man in a navy blue shirt with white stripes and khaki three quarter pants", 1),
    SetPlayerSkin(22, "A young black man in a black and orange hoody, black and orange pants and with a black hat", 1),
    SetPlayerSkin(23, "A young white man in a gray t-shirt, beige three quarter pants and with a black cap", 1),
    SetPlayerSkin(24, "A middle-aged black man in a navy blue jacket, blue jeans and navy blue cap", 1),
    SetPlayerSkin(25, "A middle-aged black man in a navy blue and white jacket and black jeans", 1),
    SetPlayerSkin(26, "A young white man in a navy blue t-shirt, beige shorts and with a gray backpack", 1),
    SetPlayerSkin(27, "A middle-aged white man in a white t-shirt, blue jeans, with a yellow hat and white gloves", 1),
    SetPlayerSkin(28, "A young black man in a brown sleeveless t-shirt, gray pants and with a brown hat", 1),
    SetPlayerSkin(29, "A middle-aged white man in a white hoody, blue jeans and with a black cap", 1),
    SetPlayerSkin(30, "A middle-aged white man in a gray sleeveless t-shirt, gray pants and with black glasses", 1),
    SetPlayerSkin(31, "A middle-aged white woman in a white t-shirt, blue jeans and with a white hat", 2),
    SetPlayerSkin(32, "An old white man in navy blue shirt, gray jeans and with a navy blue cap", 1),
    SetPlayerSkin(33, "A middle-aged white man in a black coat, black pants and with a black hat", 1),
    SetPlayerSkin(34, "A middle-aged white man in a blue shirt with gray plaid, blue jeans, with a gray hat and black glasses", 1),
    SetPlayerSkin(35, "A middle-aged white man in a pink shirt, beige three quarter pants and with a beige hat", 1),
    SetPlayerSkin(36, "A middle-aged white man in a white polo t-shirt, navy blue three quarter pants and with a navy blue cap", 1),
    SetPlayerSkin(37, "A middle-aged white man in a green polo t-shirt, khaki three quarter pants and with a red cap", 1),
    SetPlayerSkin(38, "An old white woman in a white and khaki shirt, khaki three quarter pants and with a pink headband cap", 2),
    SetPlayerSkin(39, "An old white woman in a brown sweater, navy blue skirt and with a blue and brown kerchief", 2),
    SetPlayerSkin(40, "A middle-aged white woman in a red dress", 2),
    SetPlayerSkin(41, "A young white woman in a light blue and white jacket, light blue and white pants and with a light blue hat", 2),
    -- SetPlayerSkin(42, "Jethro", 1),                                         ---> not working
    SetPlayerSkin(43, "A middle-aged white man in a purple shirt, black pants and with black glasses", 1),
    SetPlayerSkin(44, "A middle-aged white man in a blue shirt with black plaid and brown jeans", 1),
    SetPlayerSkin(45, "A young white man in green shorts and with black glasses", 1),
    SetPlayerSkin(46, "A young white man in a white shirt and blue jeans", 1),
    SetPlayerSkin(47, "A young white man in a gray shirt with black plaid, beige pants and with black glasses", 1),
    SetPlayerSkin(48, "A young white man in a blue polo t-shirt with white stripes, gray pants and black glasses", 1),
    SetPlayerSkin(49, "An old white man in a black shirt with red vest and black and red pants", 1),
    SetPlayerSkin(50, "A white man in a gray overalls and with a black kerchief", 1),
    SetPlayerSkin(51, "A young black man in a orange sleeveless t-shirt, black shorts and with a black helmet", 1),
    SetPlayerSkin(52, "A young white man in orange and white shirt, black shorts and with a gray helmet", 1),
    SetPlayerSkin(53, "A middle-aged white woman in a khaki shirt, navy blue three quarter pants and a green headband cap", 2),
    SetPlayerSkin(54, "A middle-aged white woman in a brown sweater and a purple skirt", 2),
    SetPlayerSkin(55, "A young white woman in a black dress with brown strides and brown glasses", 2),
    SetPlayerSkin(56, "A young white woman in a green sleeveless t-shirt and a gray skirt", 2),
    SetPlayerSkin(57, "An old white man in a black suit", 1),
    SetPlayerSkin(58, "A middle-aged white man in a red shirt with black plaid and gray jeans", 1),
    SetPlayerSkin(59, "A young white man in a gray shirt with purple strides and black pants", 1),
    SetPlayerSkin(60, "A young white man in a brown sweater with blue jeans", 1),
    SetPlayerSkin(61, "A middle-aged white man in a black pilot suit", 1),
    SetPlayerSkin(62, "A old white man in a ligh blue with white stripes pajamas", 1),
    -- SetPlayerSkin(63, "A young black woman in a pink bra and black skirt", 2),  --> too vulgar...
    -- SetPlayerSkin(64, "A young white woman in a black t-shirt and pink skirt", 2),  --> too vulgar...
    -- SetPlayerSkin(65, "Kendl Johnson", 1),                                  ---> not working
    SetPlayerSkin(66, "A middle-aged black man in a navy blue and white jacket and black jeans", 1),
    -- SetPlayerSkin(67, "Pool Player", 1),                                    ---> same as 66
    SetPlayerSkin(68, "An old white man in a black suit", 1),
    SetPlayerSkin(69, "A young black woman in a sleeveless jeans shirt and blue jeans", 2),
    SetPlayerSkin(70, "An old white man in a white white coat and gray pants", 1),
    SetPlayerSkin(71, "A middle-aged white man in a blue shirt, navy blue pants and with a navy blue cap", 1),
    SetPlayerSkin(72, "A middle-aged white man in a blue shirt with black plaid and blue jeans", 1),
    SetPlayerSkin(73, "A middle-aged white man in a khaki t-shirt, camouflage pants and with a blue, red and white kerchief", 1),
    -- SetPlayerSkin(74, "-", 1),                                              ---> not working
    -- SetPlayerSkin(75, "Prostitute", 1),                                     ---> too vulgar
    SetPlayerSkin(76, "A middle-aged black woman in a navy blue suit", 2),
    SetPlayerSkin(77, "A middle-aged white woman in a navy blue and green sweater, a khaki skirt and with a pink hat", 2),
    SetPlayerSkin(78, "An old white man in a red shirt with white plaid, blue jeans and with a navy blue cap and blue gloves", 1),
    SetPlayerSkin(79, "A middle-aged white man with a khaki jacket, blue pants and a navy blue hat", 1),
    SetPlayerSkin(80, "A middle-aged black man in red shorts and red boxing gloves", 1),
    -- SetPlayerSkin(81, "Boxer", 1),                                          ---> same as 80
    SetPlayerSkin(82, "A young white man in a black suit and with black glasses", 1),
    SetPlayerSkin(83, "A young black man in a white suit", 1),
    SetPlayerSkin(84, "A young black man in a blue suit and with black glasses", 1),
    -- SetPlayerSkin(85, "Prostitute", 1),                                     ---> too vulgar
    -- SetPlayerSkin(86, "Ryder with robbery mask", 1),                        ---> not working
    -- SetPlayerSkin(87, "Stripper", 1),                                       ---> too vulgar
    SetPlayerSkin(88, "An old woman in a red polo t-shirt and biege three quarter pants", 2),
    SetPlayerSkin(89, "An old woman in a ligh blue dress and with a red headband", 2),
    -- SetPlayerSkin(90, "A young woman in a brown t-shirt, a black skirt and with a green headband", 2),    --> too vulgar
    -- SetPlayerSkin(91, "Rich Woman", 2),                                     ---> same as 90
    -- SetPlayerSkin(92, "A young white woman in a navy blue swim suit", 2),             --> too vulgar
    SetPlayerSkin(93, "A young white woman in a black blouse and black jeans", 2),
    SetPlayerSkin(94, "An old white man in a white shirt, gray three quarter pants and a gray hat", 1),
    SetPlayerSkin(95, "An old man in a white shirt and blue jeans", 1),
    SetPlayerSkin(96, "A young white man in a white sleeveless t-shirt with gray strides and gray and red shorts", 1),
    SetPlayerSkin(97, "A young white man in red shorts", 1),
    SetPlayerSkin(98, "A young white man in a white shirt with a black vest and blue jeans", 1),
    -- SetPlayerSkin(99, "A young white man in a white t-shirt, black shorts and a gray helmet", 1), --> roller skater, the walk animation does not apply to him
    SetPlayerSkin(100, "A middle-aged white man with a long blonde tail, in a gray jacket, beige pants, with black glasses and brown gloves", 1),
    SetPlayerSkin(101, "A young white man with blonde hair, in a khaki jacket and white t-shirt, and black pants", 1),
    SetPlayerSkin(102, "A middle-aged black man with black hair, in a white t-shirt, purple shorts and with a purple headband", 1),
    SetPlayerSkin(103, "A middle-aged black man with a black jacket, black pants and with a purple kerchief", 1),
    SetPlayerSkin(104, "A middle-aged black man with a purple jacket, beige pants, with a black hat and glasses", 1),
    SetPlayerSkin(105, "A young black man in a green sweater, gray pants and with a green kerchief", 1),
    SetPlayerSkin(106, "A young black man with black long hair, green shirt with black strides and beige pants", 1),
    SetPlayerSkin(107, "A young black man in a green sleeveless t-shirt, black pants and with a black cap", 1),
    SetPlayerSkin(108, "A middle-aged white man in black pants and with a yellow headband", 1),
    SetPlayerSkin(109, "A middle-aged white man in a sleeveless white t-shirt, beige pants and with a yellow headband", 1),
    SetPlayerSkin(110, "A middle-aged white man in a sleeveless white t-shirt, navy blue three quarter pants and with a yellow headband", 1),
    SetPlayerSkin(111, "A middle-aged white man, black hair in a black suit", 1),
    SetPlayerSkin(112, "A middle-aged white bald man in a brown jacket, gray t-shirt and beige pants", 1),
    SetPlayerSkin(113, "A middle-aged white man with black hair and in a gray suit", 1),
    SetPlayerSkin(114, "A young white man in a gray polo with navy blue strides, gray pants and with a light blue headband", 1),
    SetPlayerSkin(115, "A young white man in a black jacket, white t-shirt, black pants and with a black cap, black glasses and a light blue headband", 1),
    SetPlayerSkin(116, "A young bald white man in a white t-shirt, beige three quarter pants and black glasses", 1),
    SetPlayerSkin(117, "A middle-aged asian man with black hair in a black suit", 1),
    SetPlayerSkin(118, "A middle-aged asian man with black hair in a black suit", 1),
    -- SetPlayerSkin(119, "Johhny Sindacco", 1),                                     ---> not working
    SetPlayerSkin(120, "A middle-aged white man with black hair in a gray suit with a black shirt", 1),
    SetPlayerSkin(121, "A bald middle-aged asian man in a white shirt with blue jeans, having tatoos on both arms", 1),
    SetPlayerSkin(122, "A young white man in a black t-shirt, khaki pants and with a black kerchief", 1),
    SetPlayerSkin(123, "A middle-aged white man with black hair, gray shirt with blue and yellow forms, black pants and with black glasses", 1),
    SetPlayerSkin(124, "A young white man with black hair in a black t-shirt and black pants", 1),
    SetPlayerSkin(125, "A middle-aged white man with black hair, in a black jacket and black pants", 1),
    -- SetPlayerSkin(126, "The Mafia", 1),                                        ---> same as 90
    SetPlayerSkin(127, "A middle-aged white man with brown hair, in a brown jacket with a light blue shirt, beige pants and with black gloves", 1),
    SetPlayerSkin(128, "A middle-aged white man with a long black hair in a khaki shirt and blue jeans", 1),
    SetPlayerSkin(129, "An old white woman with one tail white hair in a brown sweater with a brown skirt and with glasses", 2),
    SetPlayerSkin(130, "A middle-aged white woman with two tails brown hair in a navy blue shirt and a red skirt", 2),
    SetPlayerSkin(131, "A white woman with two tails brown hair in a brown t-shirt and blue jeans", 2),
    SetPlayerSkin(132, "A bald white man in a beige shirt, gray pants and with a red headband", 1),
    SetPlayerSkin(133, "A middle-aged white man with a gray tails in a khaki shirt, gray jeans and with a red cap", 1),
    SetPlayerSkin(134, "An old black man in a white shirt, gray shorts and with a khaki cap", 1),
    SetPlayerSkin(135, "An old white man with long white hair in a red shirt, khaki shorts and with a khaki winter hat", 1),
    SetPlayerSkin(136, "And old black man with one tail gray hair, gray sweater, purple pants and a red, green and yellow winter hat", 1),
    -- SetPlayerSkin(137, "A middle-aged man in a khaki t-shirt, blue three quarter jeans and with a box on head", 1),
    -- SetPlayerSkin(138, "White woman in a swim suit", 2),                       ---> TO DO
    -- SetPlayerSkin(139, "Black woman in a swim suit", 2),                       ---> TO DO
    -- SetPlayerSkin(140, "Asian woman in a swim suit", 2),                       ---> TO DO
    SetPlayerSkin(141, "A young asian woman with black hair in a black suit and with glasses", 2),
    SetPlayerSkin(142, "A middle-aged black man in a colourful t-shirt, black pants and with a colourful winter hat", 1),
    SetPlayerSkin(143, "A middle-aged black man in a light blue shirt, beige pants, with a white hat and black glasses", 1),
    SetPlayerSkin(144, "A young white man with black hair, black and white shirt, khaki pants and with a white mask", 1),
    -- SetPlayerSkin(145, "Crack Maker", 1),                                      ---> TO DO - naked woman!
    SetPlayerSkin(146, "A white young man with black hair in gray shorts", 1),
    SetPlayerSkin(147, "A middle-aged white man with brown hair in a gray suit", 1),
    SetPlayerSkin(148, "A middle-aged black woman in a light blue suit", 2), --can't lay on ground (beach)
    -- SetPlayerSkin(149, "Big Smoke Armored", 1),                                ---> Not Working
    SetPlayerSkin(150, "A young white woman with one tails blonde hail, wearing a blue suit with gray stripes", 2),
    SetPlayerSkin(151, "A young white woman with brown hair, kakhi t-shirt, blue jeans skirt and glasses", 2),
    -- SetPlayerSkin(152, "Prostitute", 1),       ---> too vulgar
    SetPlayerSkin(153, "A middle-aged white man in a black suit and a white cap", 1),
    SetPlayerSkin(154, "A young white man with blond hair in navy blue shrots", 1),
    SetPlayerSkin(155, "A young pizza delivery man in a red and yellow t-shirt, black pants and a yellow and red cap", 1),
    SetPlayerSkin(156, "An old black man in a blue shirt, black pants and with glasses", 1),
    SetPlayerSkin(157, "A middle-aged white woman with black hair in green t-shirt and blue jeans overalls", 2),
    SetPlayerSkin(158, "An old white man in khaky shirt, blue jeans overalls and a straw hat", 1),
    SetPlayerSkin(159, "A middle-aged man in gray jeans overalls and a red hat", 1),
    SetPlayerSkin(160, "An old white bald man with a gray beard in a red shirt and gray short", 1),
    SetPlayerSkin(161, "A middle-aged white man in a red shirt with purple strides, gray jeans and a brown hat", 1),
    SetPlayerSkin(162, "A middle-aged bald white man in gray jeans", 1),
    SetPlayerSkin(163, "A middle-aged black bald man in a black suit", 1),
    SetPlayerSkin(164, "A middle-aged white man with blonde hair in a black suit", 1),
    SetPlayerSkin(165, "An old white man in a black suit with black glasses", 1),
    SetPlayerSkin(166, "A middle-aged black man with black hair in a black suit with black glasses", 1),
    SetPlayerSkin(167, "A young white man in a yellow shirt and yellow pants with a chicken head", 1),
    SetPlayerSkin(168, "A middle-aged black man in a gray shirt with a white apron, khaki short and a blue hat", 1),
    SetPlayerSkin(169, "A young white woman with black hair in a black chinese dress", 2),
    SetPlayerSkin(170, "A young white man with black hair in a red shirt and gray jeans", 1),
    SetPlayerSkin(171, "A middle-aged white man with black hair in a white shirt, black vest and black pants", 1),
    SetPlayerSkin(172, "A young white woman with blonde hair, white shirt, black vest and black pants", 2),
    SetPlayerSkin(173, "A white middle-aged white man in a white sleeveless t-shirt, gray pants and with a white hat", 1),
    SetPlayerSkin(174, "A white middle-aged white man in a white shirt, black vest, purple pants, light blue badge and black glasses", 1),
    SetPlayerSkin(175, "A middle-aged white man in a light blue shirt, gray pants and a light blue badge", 1),
    SetPlayerSkin(176, "A young black man with black hair in a light blue t-shirt and black pants", 1),
    SetPlayerSkin(177, "A young white man with brown hair in a light blue t-shirt and black pants", 1),
    -- SetPlayerSkin(178, "Whore", 1),                         ---> too vulgar
    SetPlayerSkin(179, "A middle-aged white man with black hair and beard in a khaki sleeveless t-shirt and a three quarter khaki pants", 1),
    SetPlayerSkin(180, "A young black man with black hair in a black and white shirt, and gray pants", 1),
    -- SetPlayerSkin(181, "Punk", 1),                     ---> too weird
    SetPlayerSkin(182, "An old black man with black hair in a light blue shirt and light blue shorts", 1),
    SetPlayerSkin(183, "A middle aged black man with black hair, in a khaki shirt and gray pants", 1),
    SetPlayerSkin(184, "A middle aged white man with black hair in a white and blue blouse and gray jeans", 1),
    SetPlayerSkin(185, "A young white man with black hair in a purple shirt with white strides, black pants and black glasses", 1),
    SetPlayerSkin(186, "A young white man with black hair in a brown suit and a white shrit", 1),
    SetPlayerSkin(187, "A middle-aged white man with black hair in a purple suit", 1),
    SetPlayerSkin(188, "A young man with black hair in a green shirt and gray jeans", 1),
    SetPlayerSkin(189, "A young white man with black hair, red vest, white shirt and black pants", 1),
    SetPlayerSkin(190, "A young black woman with brown hair, red shirt and black running pants", 2),
    SetPlayerSkin(191, "A young white woman with brown short hair, khaki t-shirt and khaki pants", 2),
    SetPlayerSkin(192, "A young white woman with blonde hair, gray sleeveless t-shirt and gray jeans", 2),
    SetPlayerSkin(193, "A young white woman with black hair, red t-shirt and gray pants", 2),
    SetPlayerSkin(194, "A young white woman with brown hair, white shirt, black vest and black pants", 2),
    SetPlayerSkin(195, "A young black woman with a black shirt, white pants and gray kerchief", 2),
    SetPlayerSkin(196, "An old woman with gray hair in a green shirt and a brown skirt", 2),
    SetPlayerSkin(197, "An old woman in a light blue sleeveless shirt, red skirt and red kerchief", 2),
    SetPlayerSkin(198, "A middle-aged woman with brown hair, purple shirt and blue jeans", 2),
    -- SetPlayerSkin(199, "Farm - Town inhabitant", 1),      ---> too weird
    -- SetPlayerSkin(200, "Hillbilly", 1),            ---> too weird
    SetPlayerSkin(201, "A young woman with brown hair, short t-shirt, gray jeans and gray cap", 2),
    SetPlayerSkin(202, "A middle-aged man with a gray t-shirt, gray jeans and gray cap", 1),
    SetPlayerSkin(203, "A middle-aged asian man with black hair in a black karate uniform", 1),
    SetPlayerSkin(204, "A middle-aged white man with brown hair in a black karate uniform", 1),
    -- SetPlayerSkin(205, "Burger Shot Cashier", 1),       ---> too weird
    SetPlayerSkin(206, "A middle-aged white bald man with a khaki t-shirt and black jeans", 1),
    ---- SetPlayerSkin(207, "Prostitute", 1),              ---> too vulgar
    -- SetPlayerSkin(208, "An old white bald man with a red t-shirt, white apron and brown pants", 1),
    SetPlayerSkin(209, "A middle-aged asian man with black hair in a light gray shirt and black pants", 1),
    SetPlayerSkin(210, "A young white woman with brown hair in a black shirt and black jeans", 1),
    -- SetPlayerSkin(211, "Clothes shop staff", 1),            ---> too weird
    -- SetPlayerSkin(212, "Homeless", 1),                      ---> too weird
    -- SetPlayerSkin(213, "Weird old man", 1),                 ---> too weird
    SetPlayerSkin(214, "A young white woman with black hair in a white dress", 2),
    SetPlayerSkin(215, "A young black woman with black hair in a yellow shirt, white pants and a yellow hat", 2),
    SetPlayerSkin(216, "A young white woman with brown hair in a light purple dress", 2),
    SetPlayerSkin(217, "A yonung white man with brown hair in a gray shirt and black jeans", 1),
    SetPlayerSkin(218, "An old black woman with gray hair in a pink shirt, brown vest and a multicolor skirt", 2),
    SetPlayerSkin(219, "A middle-aged black woman with brown hair in a red dress", 2),
    SetPlayerSkin(220, "A middle-aged white man with a beard in a hippie costume", 1),
    SetPlayerSkin(221, "A middle-aged black man with black hair and beard in a white shirt and light khaki pants", 1),
    SetPlayerSkin(222, "A middle-aged black man with black hair and beard in a black and brown t-shirt and gray jeans", 1),
    SetPlayerSkin(223, "A young white man with brown hair in a pink shirt and black pants", 1),
    SetPlayerSkin(224, "A middle-aged asian woman with black hair in a brown and purple shirt and purple pants", 2),
    SetPlayerSkin(225, "A middle-aged asian woman with black hair in a multicolor shirt and light blue jeans", 2),
    SetPlayerSkin(226, "A young asian woman with black hair in a light pink shirt and a gray shirt", 2),
    SetPlayerSkin(227, "An old bald asian man in a black suit", 1),
    SetPlayerSkin(228, "An old asian man with gray hair in a black suit", 1),
    SetPlayerSkin(229, "An old asian man with gray hair in a white shirt and gray jeans", 1),
    -- SetPlayerSkin(230, "Homeless", 1),                   ---> too weird
    SetPlayerSkin(231, "An old white woman with white hair in a green shirt and red shorts with black stripes", 2),
    SetPlayerSkin(232, "A middle-aged woman with brown hair in a red shirt with black strides and a skirt", 2),
    SetPlayerSkin(233, "A young white woman with brown hair in a white blouse and gray jeans", 2),
    SetPlayerSkin(234, "An old white man with white hair in a khaki t-shirt, blue jeans and with black glasses", 1),
    SetPlayerSkin(235, "An old blad white man in a colourful shirt and cream pants", 1),
    SetPlayerSkin(236, "An old white man with white hair and moustache in a green shrit with black stripes and brown pants", 1),
    ---- SetPlayerSkin(237, "Prostitute", 1),              ---> too vulgar
    ---- SetPlayerSkin(238, "Prostitute", 1),              ---> too vulgar
    -- SetPlayerSkin(239, "Homeless", 1),                  ---> too weird
    SetPlayerSkin(240, "A young white man with brown hair in a white shirt, gray vest and black pants", 1),
    SetPlayerSkin(241, "A middle-aged white man with black hair in a navy blue shirt, three quarters gray jeans and with black glasses", 1),
    SetPlayerSkin(242, "A middle-aged white man in a white sleeveless t-shirt, gray three quarters pants and with black glasses", 1),
    ---- SetPlayerSkin(243, "Prostitute", 1),               ---> too vulgar
    -- SetPlayerSkin(244, "Stripper", 1),                   ---> too vulgar
    ---- SetPlayerSkin(245, "Prostitute", 1),               ---> too vulgar
    -- SetPlayerSkin(246, "Stripper", 1),                   ---> too vulgar
    SetPlayerSkin(247, "A young white man with brown hair in a gray best, gray jeans and a black kerchief", 1),
    SetPlayerSkin(248, "A young white man with blonde hair, black jacket, black pants and with a red band", 1),
    -- SetPlayerSkin(249, "Pimp", 1),                       ---> too weird
    SetPlayerSkin(250, "A young white man with brown hair in a green t-shirt and gray jeans", 1),
    -- SetPlayerSkin(251, "Lifeguard", 1),                  ---> too vulgar
    -- SetPlayerSkin(252, "Naked Valet", 1),                ---> too weird
    SetPlayerSkin(253, "A midle-aged black man with a gray moustache in a military unifrom", 1),
    -- SetPlayerSkin(254, "Biker Drug Dealer", 1),          ---> same as 247
    SetPlayerSkin(255, "A young white man with a black moustache in a black suit with a black hat", 1),
    -- SetPlayerSkin(256, "Stripper", 1),                   ---> too vulgar
    -- SetPlayerSkin(257, "Stripper", 1),                   ---> too vulgar
    SetPlayerSkin(258, "A middle-aged white man with black hair in a gray shirt and cream pants", 1),
    SetPlayerSkin(259, "A middle-aged white man with black hair in a blue shirt and cream shorts", 1),
    SetPlayerSkin(260, "A young black man in a orange shirt, gray jeans and a yellow helmet", 1),
    SetPlayerSkin(261, "A middle-aged white man in a shirt, gray jeans and with a black cap", 1),
    SetPlayerSkin(262, "A middle-aged bald black man in a green shirt and gray shorts", 1),
    SetPlayerSkin(263, "A middle-aged asian woman with brown hair in a colourful dress", 2),
    -- SetPlayerSkin(264, "Clown(Ice - cream Van Driver)", 1),                    ---> too weird
    SetPlayerSkin(265, "A middle-aged bald black man with a black moustache in a black police uniform", 1),
    SetPlayerSkin(266, "A middle-aged white man with blonde hair in a black police uniform", 1),
    SetPlayerSkin(267, "A middle aged white man with black hair in a black police uniform", 1),
    SetPlayerSkin(268, "A young white man with blonde hair in a blue shirt and blue three quarter pants", 1),
    SetPlayerSkin(269, "A middle-aged black man with a black beard in a green shirt, black pants, with a black hat and glases", 1),
    SetPlayerSkin(270, "A middle-aged black man with a black beard in a green shirt, black pants and with a green hat", 1),
    SetPlayerSkin(271, "A middle-aged black man in a green shirt, black jeans, with a black hat and black glasses", 1),
    SetPlayerSkin(272, "A middle-aged black man with black hair in a black jacket and cream pants", 1),
    -- SetPlayerSkin(273, "A middle-aged black man with black hair in a white shirt, navy blue pants and with gloves", 1), non-existent
    SetPlayerSkin(274, "A middle-aged black man with black hair in a white shirt, navy blue pants and with gloves", 1),
    SetPlayerSkin(275, "A middle-aged white man with black hair in a light blue shirt, navy pants and with gloves", 1),
    SetPlayerSkin(276, "A middle-aged white man with black hair in a green shirt, khaki pants and with gloves", 1),
    SetPlayerSkin(277, "A middle-aged white man in a cream firefighter uniform", 1),
    SetPlayerSkin(278, "A middle-aged black man with a black moustache in a cream firefighter uniform", 1),
    SetPlayerSkin(279, "A middle-aged white man with a black moustache in a black firefighter uniform", 1),
    SetPlayerSkin(280, "A young white man with black hair in a black police uniform", 1),
    SetPlayerSkin(281, "A middle-aged white man with black hair and moustache in a black police uniform", 1),
    SetPlayerSkin(282, "A middle-aged white man with brown hair in a cream police uniform", 1),
    SetPlayerSkin(283, "A middle-aged white man in a police uniform and a white hat", 1),
    SetPlayerSkin(284, "A middle-aged black man in a black police uniform, white helmet and black glasses", 1),
    -- SetPlayerSkin(285, "S.W.A.T Special Forces", 1),
    SetPlayerSkin(286, "A middle-aged white man with gray hair in a police uniform", 1),
    SetPlayerSkin(287, "A middle-aged white man in a military uniform with a cap", 1),
    SetPlayerSkin(288, "A middle-aged white man in a police uniform with a hat", 1),
    -- SetPlayerSkin(289, "Zero", 1),
    SetPlayerSkin(290, "A middle-aged white man with brown hair in a black blouse and cream pants", 1),
    SetPlayerSkin(291, "A young man with brown hair in a light blue jeans vest and black jeans", 1),
    SetPlayerSkin(292, "A young white man with black hair in a sleeveless white t-shirt and gray pants", 1),
    -- SetPlayerSkin(293, "Jeffery \"OG Loc\" Martin / Cross", 1),
    SetPlayerSkin(294, "A middle-aged white man with black hair in a black suit and black glasses", 1),
    SetPlayerSkin(295, "A middle-aged white man with brown hair in a suit", 1),
    SetPlayerSkin(296, "A middle-aged black man with black hair in a purple suit", 1),
    SetPlayerSkin(297, "A middle-aged black man with black hair and beard, in a navy blue blouse and jeans", 1),
    SetPlayerSkin(298, "A young white woman with brown hair in a sleeveless black t-shirt and black pants", 2),
    SetPlayerSkin(299, "A young white man with black hair in a black jacked and khaki pants", 1),
    -- SetPlayerSkin(300, "Los Santos Police Officer(Without gun holster)", 1),
    -- SetPlayerSkin(301, "San Fierro Police Officer(Without gun holster)", 1),
    SetPlayerSkin(302, "A young black man in a khaki jacked, black pants and red hat", 1),
    SetPlayerSkin(303, "A middle-aged white man with brown hair in a purple suit", 1),
    SetPlayerSkin(304, "A young black woman with black hair in a black shirt, black pants and with a cream hat", 2),
    -- SetPlayerSkin(305, "Las Venturas Police Officer(Without uniform)", 1),
    SetPlayerSkin(306, "A young white man in a khaki shirt, black three quarter pants, red had and with glasses", 1),
    SetPlayerSkin(307, "A middle-aged white man with black hair and a black moustache in a white and blue shirt and gray pants", 1),
    SetPlayerSkin(308, "A young white man with black hair in a navy blue t-shirt and cream pants", 1),
    -- SetPlayerSkin(309, "Las Venturas Police Officer", 1),
    SetPlayerSkin(310, "A young black man with black hair in a brown shirt and jeans", 1),
    -- SetPlayerSkin(311, "Desert Sheriff(Without hat)", 1)
}

function SetPlayerSkin:Apply(requiredAttributes)
    self.isTaken = true
    local player = self.Performer
    if not player then
        player = self.TargetItem
    end
    player:setModel(self.Id)
    player:setData('skinDescription', self.Description)

    if requiredAttributes then
        for k,v in pairs(requiredAttributes) do
            if DEBUG then
                print('SetPlayerSkin:Apply: set data '..k:lower()..'='..v)
            end
            player:setData(k:lower(), v)
        end
        if (player:getData('name')) then
            local splitName = player:getData('name'):split(' ')
            if #splitName == 2 then
                player:setData('first_name', splitName[1])
                player:setData('surname', splitName[2])
            else
                player:setData('first_name', player:getData('name'))
                player:setData('surname', '')
            end
        else
            error('The graph does not contain a name for the actor with gender' .. self.Gender)
        end
    else
        if self.Gender == 2 then
            player:setData('first_name', PickRandom(SetPlayerSkin.FemaleNames))
        else
            player:setData('first_name', PickRandom(SetPlayerSkin.MaleNames))
        end
        player:setData('surname', PickRandom(SetPlayerSkin.FamilyNames))
    end
    player:setData('name', trim(player:getData('first_name')..' '..player:getData('surname')))
    player:setData('genderNominative', self.Nominative)
    player:setData('genderGenitive', self.Genitive)
    player:setData('gender', self.Gender)

    local event = {id = player:getData('id'), Name = player:getData('name'), Description = player:getData('skinDescription'), Gender = player:getData('genderNominative')}
end

function SetPlayerSkin:GetDynamicString()
    return 'return SetPlayerSkin('..self.Id..', "'..self.Description..'")'
end