--See https://wiki.multitheftauto.com/wiki/Character_Skins for details
SetPlayerSkin = class(StoryActionBase, function(o, id, description) --maybe add gender here
    StoryActionBase.init(o, {description = description})
    o.Id = id
    o.isTaken = false
end)

SetPlayerSkin.MaleNames = {
'Liam',
'Noah',
'William',
'James',
'Logan',
'Benjamin',
'Mason',
'Elijah',
'Oliver',
'Jacob',
'Lucas',
'Michael',
'Alexander',
'Ethan',
'Daniel',
'Matthew',
'Aiden',
'Henry',
'Joseph',
'Jackson',
'Samuel',
'Sebastian',
'David',
'Carter',
'Wyatt',
'Jayden',
'John',
'Owen',
'Dylan',
'Luke',
'Gabriel',
'Anthony',
'Isaac',
'Grayson',
'Jack',
'Julian',
'Levi',
'Christopher',
'Joshua',
'Andrew',
'Lincoln',
'Mateo',
'Ryan',
'Jaxon',
'Nathan',
'Aaron',
'Isaiah',
'Thomas',
'Charles',
'Caleb',
'Josiah',
'Christian',
'Hunter',
'Eli',
'Jonathan',
'Connor',
'Landon',
'Adrian',
'Asher',
'Cameron',
'Leo',
'Theodore',
'Jeremiah',
'Hudson',
'Robert',
'Easton',
'Nolan',
'Nicholas',
'Ezra',
'Colton',
'Angel',
'Brayden',
'Jordan',
'Dominic',
'Austin',
'Ian',
'Adam',
'Elias',
'Jaxson',
'Greyson',
'Jose',
'Ezekiel',
'Carson',
'Evan',
'Maverick',
'Bryson',
'Jace',
'Cooper',
'Xavier',
'Parker',
'Roman',
'Jason',
'Santiago',
'Chase',
'Sawyer',
'Gavin',
'Leonardo',
'Kayden',
'Ayden',
'Jameson',
'Kevin',
'Bentley',
'Zachary',
'Everett',
'Axel',
'Tyler',
'Micah',
'Vincent',
'Weston',
'Miles',
'Wesley',
'Nathaniel',
'Harrison',
'Brandon',
'Cole',
'Declan',
'Luis',
'Braxton',
'Damian',
'Silas',
'Tristan',
'Ryder',
'Bennett',
'George',
'Emmett',
'Justin',
'Kai',
'Max',
'Diego',
'Luca',
'Ryker',
'Carlos',
'Maxwell',
'Kingston',
'Ivan',
'Maddox',
'Juan',
'Ashton',
'Jayce',
'Rowan',
'Kaiden',
'Giovanni',
'Eric',
'Jesus',
'Calvin',
'Abel',
'King',
'Camden',
'Amir',
'Blake',
'Alex',
'Brody',
'Malachi',
'Emmanuel',
'Jonah',
'Beau',
'Jude',
'Antonio',
'Alan',
'Elliott',
'Elliot',
'Waylon',
'Xander',
'Timothy',
'Victor',
'Bryce',
'Finn',
'Brantley',
'Edward',
'Abraham',
'Patrick',
'Grant',
'Karter',
'Hayden',
'Richard',
'Miguel',
'Joel',
'Gael',
'Tucker',
'Rhett',
'Avery',
'Steven',
'Graham',
'Kaleb',
'Jasper',
'Jesse',
'Matteo',
'Dean',
'Zayden',
'Preston',
'August',
'Oscar',
'Jeremy',
'Alejandro',
'Marcus',
'Dawson',
'Lorenzo',
'Messiah',
'Zion',
'Maximus',
'River',
'Zane',
'Mark',
'Brooks',
'Nicolas',
'Paxton',
'Judah',
'Emiliano',
'Kaden',
'Bryan',
'Kyle',
'Myles',
'Peter',
'Charlie',
'Kyrie',
'Thiago',
'Brian',
'Kenneth',
'Andres',
'Lukas',
'Aidan',
'Jax',
'Caden',
'Milo',
'Paul',
'Beckett',
'Brady',
'Colin',
'Omar',
'Bradley',
'Javier',
'Knox',
'Jaden',
'Barrett',
'Israel',
'Matias',
'Jorge',
'Zander',
'Derek',
'Josue',
'Cayden',
'Holden',
'Griffin',
'Arthur',
'Leon',
'Felix',
'Remington',
'Jake',
'Killian',
'Clayton',
'Sean',
'Adriel',
'Riley',
'Archer',
'Legend',
'Erick',
'Enzo',
'Corbin',
'Francisco',
'Dallas',
'Emilio',
'Gunner',
'Simon',
'Andre',
'Walter',
'Damien',
'Chance',
'Phoenix',
'Colt',
'Tanner',
'Stephen',
'Kameron',
'Tobias',
'Manuel',
'Amari',
'Emerson',
'Louis',
'Cody',
'Finley',
'Iker',
'Martin',
'Rafael',
'Nash',
'Beckham',
'Cash',
'Karson',
'Rylan',
'Reid',
'Theo',
'Ace',
'Eduardo',
'Spencer',
'Raymond',
'Maximiliano',
'Anderson',
'Ronan',
'Lane',
'Cristian',
'Titus',
'Travis',
'Jett',
'Ricardo',
'Bodhi',
'Gideon',
'Jaiden',
'Fernando',
'Mario',
'Conor',
'Keegan',
'Ali',
'Cesar',
'Ellis',
'Jayceon',
'Walker',
'Cohen',
'Arlo',
'Hector',
'Dante',
'Kyler',
'Garrett',
'Donovan',
'Seth',
'Jeffrey',
'Tyson',
'Jase',
'Desmond',
'Caiden',
'Gage',
'Atlas',
'Major',
'Devin',
'Edwin',
'Angelo',
'Orion',
'Conner',
'Julius',
'Marco',
'Jensen',
'Daxton',
'Peyton',
'Zayn',
'Collin',
'Jaylen',
'Dakota',
'Prince',
'Johnny',
'Kayson',
'Cruz',
'Hendrix',
'Atticus',
'Troy',
'Kane',
'Edgar',
'Sergio',
'Kash',
'Marshall',
'Johnathan',
'Romeo',
'Shane',
'Warren',
'Joaquin',
'Wade',
'Leonel',
'Trevor',
'Dominick',
'Muhammad',
'Erik',
'Odin',
'Quinn',
'Jaxton',
'Dalton',
'Nehemiah',
'Frank',
'Grady',
'Gregory',
'Andy',
'Solomon',
'Malik',
'Rory',
'Clark',
'Reed',
'Harvey',
'Zayne',
'Jay',
'Jared',
'Noel',
'Shawn',
'Fabian',
'Ibrahim',
'Adonis',
'Ismael',
'Pedro',
'Leland',
'Malakai',
'Malcolm',
'Alexis',
'Kason',
'Porter',
'Sullivan',
'Raiden',
'Allen',
'Ari',
'Russell',
'Princeton',
'Winston',
'Kendrick',
'Roberto',
'Lennox',
'Hayes',
'Finnegan',
'Nasir',
'Kade',
'Nico',
'Emanuel',
'Landen',
'Moises',
'Ruben',
'Hugo',
'Abram',
'Adan',
'Khalil',
'Zaiden',
'Augustus',
'Marcos',
'Philip',
'Phillip',
'Cyrus',
'Esteban',
'Braylen',
'Albert',
'Bruce',
'Kamden',
'Lawson',
'Jamison',
'Sterling',
'Damon',
'Gunnar',
'Kyson',
'Luka',
'Franklin',
'Ezequiel',
'Pablo',
'Derrick',
'Zachariah',
'Cade',
'Jonas',
'Dexter',
'Kolton',
'Remy',
'Hank',
'Tate',
'Trenton',
'Kian',
'Drew',
'Mohamed',
'Dax',
'Rocco',
'Bowen',
'Mathias',
'Ronald',
'Francis',
'Matthias',
'Milan',
'Maximilian',
'Royce',
'Skyler',
'Corey',
'Kasen',
'Drake',
'Gerardo',
'Jayson',
'Sage',
'Braylon',
'Benson',
'Moses',
'Alijah',
'Rhys',
'Otto',
'Oakley',
'Armando',
'Jaime',
'Nixon',
'Saul',
'Scott',
'Brycen',
'Ariel',
'Enrique',
'Donald',
'Chandler',
'Asa',
'Eden',
'Davis',
'Keith',
'Frederick',
'Rowen',
'Lawrence',
'Leonidas',
'Aden',
'Julio',
'Darius',
'Johan',
'Deacon',
'Cason',
'Danny',
'Nikolai',
'Taylor',
'Alec',
'Royal',
'Armani',
'Kieran',
'Luciano',
'Omari',
'Rodrigo',
'Arjun',
'Ahmed',
'Brendan',
'Cullen',
'Raul',
'Raphael',
'Ronin',
'Brock',
'Pierce',
'Alonzo',
'Casey',
'Dillon',
'Uriel',
'Dustin',
'Gianni',
'Roland',
'Landyn',
'Kobe',
'Dorian',
'Emmitt',
'Ryland',
'Apollo',
'Aarav',
'Roy',
'Duke',
'Quentin',
'Sam',
'Lewis',
'Tony',
'Uriah',
'Dennis',
'Moshe',
'Isaias',
'Braden',
'Quinton',
'Cannon',
'Ayaan',
'Mathew',
'Kellan',
'Niko',
'Edison',
'Izaiah',
'Jerry',
'Gustavo',
'Jamari',
'Marvin',
'Mauricio',
'Ahmad',
'Mohammad',
'Justice',
'Trey',
'Elian',
'Mohammed',
'Sincere',
'Yusuf',
'Arturo',
'Callen',
'Rayan',
'Keaton',
'Wilder',
'Mekhi',
'Memphis',
'Cayson',
'Conrad',
'Kaison',
'Kyree',
'Soren',
'Colby',
'Bryant',
'Lucian',
'Alfredo',
'Cassius',
'Marcelo',
'Nikolas',
'Brennan',
'Darren',
'Jasiah',
'Jimmy',
'Lionel',
'Reece',
'Ty',
'Chris',
'Forrest',
'Korbin',
'Tatum',
'Jalen',
'Santino',
'Case',
'Leonard',
'Alvin',
'Issac',
'Bo',
'Quincy',
'Mack',
'Samson',
'Rex',
'Alberto',
'Callum',
'Curtis',
'Hezekiah',
'Finnley',
'Briggs',
'Kamari',
'Zeke',
'Raylan',
'Neil',
'Titan',
'Julien',
'Kellen',
'Devon',
'Kylan',
'Roger',
'Axton',
'Carl',
'Douglas',
'Larry',
'Crosby',
'Fletcher',
'Makai',
'Nelson',
'Hamza',
'Lance',
'Alden',
'Gary',
'Wilson',
'Alessandro',
'Ares',
'Kashton',
'Bruno',
'Jakob',
'Stetson',
'Zain',
'Cairo',
'Nathanael',
'Byron',
'Harry',
'Harley',
'Mitchell',
'Maurice',
'Orlando',
'Kingsley',
'Kaysen',
'Sylas',
'Trent',
'Ramon',
'Boston',
'Lucca',
'Noe',
'Jagger',
'Reyansh',
'Vihaan',
'Randy',
'Thaddeus',
'Lennon',
'Kannon',
'Kohen',
'Tristen',
'Valentino',
'Maxton',
'Salvador',
'Abdiel',
'Langston',
'Rohan',
'Kristopher',
'Yosef',
'Rayden',
'Lee',
'Callan',
'Tripp',
'Deandre',
'Joe',
'Morgan',
'Dariel',
'Colten',
'Reese',
'Jedidiah',
'Ricky',
'Bronson',
'Terry',
'Eddie',
'Jefferson',
'Lachlan',
'Layne',
'Clay',
'Madden',
'Jamir',
'Tomas',
'Kareem',
'Stanley',
'Brayan',
'Amos',
'Kase',
'Kristian',
'Clyde',
'Ernesto',
'Tommy',
'Casen',
'Ford',
'Crew',
'Braydon',
'Brecken',
'Hassan',
'Axl',
'Boone',
'Leandro',
'Samir',
'Jaziel',
'Magnus',
'Abdullah',
'Yousef',
'Branson',
'Jadiel',
'Jaxen',
'Layton',
'Franco',
'Ben',
'Grey',
'Kelvin',
'Chaim',
'Demetrius',
'Blaine',
'Ridge',
'Colson',
'Melvin',
'Anakin',
'Aryan',
'Lochlan',
'Jon',
'Canaan',
'Dash',
'Zechariah',
'Alonso',
'Otis',
'Zaire',
'Marcel',
'Brett',
'Stefan',
'Aldo',
'Jeffery',
'Baylor',
'Talon',
'Dominik',
'Flynn',
'Carmelo',
'Dane',
'Jamal',
'Kole',
'Enoch',
'Graysen',
'Kye',
'Vicente',
'Fisher',
'Ray',
'Fox',
'Jamie',
'Rey',
'Zaid',
'Allan',
'Emery',
'Gannon',
'Joziah',
'Rodney',
'Juelz',
'Sonny',
'Terrance',
'Zyaire',
'Augustine',
'Cory',
'Felipe',
'Aron',
'Jacoby',
'Harlan',
'Marc',
'Bobby',
'Joey',
'Anson',
'Huxley',
'Marlon',
'Anders',
'Guillermo',
'Payton',
'Castiel',
'Damari',
'Shepherd',
'Azariah',
'Harold',
'Harper',
'Henrik',
'Houston',
'Kairo',
'Willie',
'Elisha',
'Ameer',
'Emory',
'Skylar',
'Sutton',
'Alfonso',
'Brentley',
'Toby',
'Blaze',
'Eugene',
'Shiloh',
'Wayne',
'Darian',
'Gordon',
'London',
'Bodie',
'Jordy',
'Jermaine',
'Denver',
'Gerald',
'Merrick',
'Musa',
'Vincenzo',
'Kody',
'Yahir',
'Brodie',
'Trace',
'Darwin',
'Tadeo',
'Bentlee',
'Billy',
'Hugh',
'Reginald',
'Vance',
'Westin',
'Cain',
'Arian',
'Dayton',
'Javion',
'Terrence',
'Brysen',
'Jaxxon',
'Thatcher',
'Landry',
'Rene',
'Westley',
'Miller',
'Alvaro',
'Cristiano',
'Eliseo',
'Ephraim',
'Adrien',
'Jerome',
'Khalid',
'Aydin',
'Mayson',
'Alfred',
'Duncan',
'Junior',
'Kendall',
'Zavier',
'Koda',
'Maison',
'Caspian',
'Maxim',
'Kace',
'Zackary',
'Rudy',
'Coleman',
'Keagan',
'Kolten',
'Maximo',
'Dario',
'Davion',
'Kalel',
'Briar',
'Jairo',
'Misael',
'Rogelio',
'Terrell',
'Heath',
'Micheal',
'Wesson',
'Aaden',
'Brixton',
'Draven',
'Xzavier',
'Darrell',
'Keanu',
'Ronnie',
'Konnor',
'Will',
'Dangelo',
'Frankie',
'Kamryn',
'Salvatore',
'Santana',
'Shaun',
'Coen',
'Leighton',
'Mustafa',
'Reuben',
'Ayan',
'Blaise',
'Dimitri',
'Keenan',
'Van',
'Achilles',
'Channing',
'Ishaan',
'Wells',
'Benton',
'Lamar',
'Nova',
'Yahya',
'Dilan',
'Gibson',
'Camdyn',
'Ulises',
'Alexzander',
'Valentin',
'Shepard',
'Alistair',
'Eason',
'Kaiser',
'Leroy',
'Zayd',
'Camilo',
'Markus',
'Foster',
'Davian',
'Dwayne',
'Jabari',
'Judson',
'Koa',
'Yehuda',
'Lyric',
'Tristian',
'Agustin',
'Bridger',
'Vivaan',
'Brayson',
'Emmet',
'Marley',
'Mike',
'Nickolas',
'Kenny',
'Leif',
'Bjorn',
'Ignacio',
'Rocky',
'Chad',
'Gatlin',
'Greysen',
'Kyng',
'Randall',
'Reign',
'Vaughn',
'Jessie',
'Louie',
'Shmuel',
'Zahir',
'Ernest',
'Javon',
'Khari',
'Reagan',
'Avi',
'Ira',
'Ledger',
'Simeon',
'Yadiel',
'Maddux',
'Seamus',
'Jad',
'Jeremias',
'Kylen',
'Rashad',
'Santos',
'Cedric',
'Craig',
'Dominique',
'Gianluca',
'Jovanni',
'Bishop',
'Brenden',
'Anton',
'Camron',
'Giancarlo',
'Lyle',
'Alaric',
'Decker',
'Eliezer',
'Ramiro',
'Yisroel',
'Howard',
'Jaxx'
}

SetPlayerSkin.FemaleNames = {
'Emma',
'Olivia',
'Ava',
'Isabella',
'Sophia',
'Mia',
'Charlotte',
'Amelia',
'Evelyn',
'Abigail',
'Harper',
'Emily',
'Elizabeth',
'Avery',
'Sofia',
'Ella',
'Madison',
'Scarlett',
'Victoria',
'Aria',
'Grace',
'Chloe',
'Camila',
'Penelope',
'Riley',
'Layla',
'Lillian',
'Nora',
'Zoey',
'Mila',
'Aubrey',
'Hannah',
'Lily',
'Addison',
'Eleanor',
'Natalie',
'Luna',
'Savannah',
'Brooklyn',
'Leah',
'Zoe',
'Stella',
'Hazel',
'Ellie',
'Paisley',
'Audrey',
'Skylar',
'Violet',
'Claire',
'Bella',
'Aurora',
'Lucy',
'Anna',
'Samantha',
'Caroline',
'Genesis',
'Aaliyah',
'Kennedy',
'Kinsley',
'Allison',
'Maya',
'Sarah',
'Madelyn',
'Adeline',
'Alexa',
'Ariana',
'Elena',
'Gabriella',
'Naomi',
'Alice',
'Sadie',
'Hailey',
'Eva',
'Emilia',
'Autumn',
'Quinn',
'Nevaeh',
'Piper',
'Ruby',
'Serenity',
'Willow',
'Everly',
'Cora',
'Kaylee',
'Lydia',
'Aubree',
'Arianna',
'Eliana',
'Peyton',
'Melanie',
'Gianna',
'Isabelle',
'Julia',
'Valentina',
'Nova',
'Clara',
'Vivian',
'Reagan',
'Mackenzie',
'Madeline',
'Brielle',
'Delilah',
'Isla',
'Rylee',
'Katherine',
'Sophie',
'Josephine',
'Ivy',
'Liliana',
'Jade',
'Maria',
'Taylor',
'Hadley',
'Kylie',
'Emery',
'Adalynn',
'Natalia',
'Annabelle',
'Faith',
'Alexandra',
'Ximena',
'Ashley',
'Brianna',
'Raelynn',
'Bailey',
'Mary',
'Athena',
'Andrea',
'Leilani',
'Jasmine',
'Lyla',
'Margaret',
'Alyssa',
'Adalyn',
'Arya',
'Norah',
'Khloe',
'Kayla',
'Eden',
'Eliza',
'Rose',
'Ariel',
'Melody',
'Alexis',
'Isabel',
'Sydney',
'Juliana',
'Lauren',
'Iris',
'Emerson',
'London',
'Morgan',
'Lilly',
'Charlie',
'Aliyah',
'Valeria',
'Arabella',
'Sara',
'Finley',
'Trinity',
'Ryleigh',
'Jordyn',
'Jocelyn',
'Kimberly',
'Esther',
'Molly',
'Valerie',
'Cecilia',
'Anastasia',
'Daisy',
'Reese',
'Laila',
'Mya',
'Amy',
'Teagan',
'Amaya',
'Elise',
'Harmony',
'Paige',
'Adaline',
'Fiona',
'Alaina',
'Nicole',
'Genevieve',
'Lucia',
'Alina',
'Mckenzie',
'Callie',
'Payton',
'Eloise',
'Brooke',
'Londyn',
'Mariah',
'Julianna',
'Rachel',
'Daniela',
'Gracie',
'Catherine',
'Angelina',
'Presley',
'Josie',
'Harley',
'Adelyn',
'Vanessa',
'Makayla',
'Parker',
'Juliette',
'Amara',
'Marley',
'Lila',
'Ana',
'Rowan',
'Alana',
'Michelle',
'Malia',
'Rebecca',
'Brooklynn',
'Brynlee',
'Summer',
'Sloane',
'Leila',
'Sienna',
'Adriana',
'Sawyer',
'Kendall',
'Juliet',
'Destiny',
'Alayna',
'Elliana',
'Diana',
'Hayden',
'Ayla',
'Dakota',
'Angela',
'Noelle',
'Rosalie',
'Joanna',
'Jayla',
'Alivia',
'Lola',
'Emersyn',
'Georgia',
'Selena',
'June',
'Daleyza',
'Tessa',
'Maggie',
'Jessica',
'Remi',
'Delaney',
'Camille',
'Vivienne',
'Hope',
'Mckenna',
'Gemma',
'Olive',
'Alexandria',
'Blakely',
'Izabella',
'Catalina',
'Raegan',
'Journee',
'Gabrielle',
'Lucille',
'Ruth',
'Amiyah',
'Evangeline',
'Blake',
'Thea',
'Amina',
'Giselle',
'Lilah',
'Melissa',
'River',
'Kate',
'Adelaide',
'Charlee',
'Vera',
'Leia',
'Gabriela',
'Zara',
'Jane',
'Journey',
'Elaina',
'Miriam',
'Briella',
'Stephanie',
'Cali',
'Ember',
'Lilliana',
'Aniyah',
'Logan',
'Kamila',
'Brynn',
'Ariella',
'Makenzie',
'Annie',
'Mariana',
'Kali',
'Haven',
'Elsie',
'Nyla',
'Paris',
'Lena',
'Freya',
'Adelynn',
'Lyric',
'Camilla',
'Sage',
'Jennifer',
'Paislee',
'Talia',
'Alessandra',
'Juniper',
'Fatima',
'Raelyn',
'Amira',
'Arielle',
'Phoebe',
'Kinley',
'Ada',
'Nina',
'Ariah',
'Samara',
'Myla',
'Brinley',
'Cassidy',
'Maci',
'Aspen',
'Allie',
'Keira',
'Kaia',
'Makenna',
'Amanda',
'Heaven',
'Joy',
'Lia',
'Madilyn',
'Gracelyn',
'Laura',
'Evelynn',
'Lexi',
'Haley',
'Miranda',
'Kaitlyn',
'Daniella',
'Felicity',
'Jacqueline',
'Evie',
'Angel',
'Danielle',
'Ainsley',
'Dylan',
'Kiara',
'Millie',
'Jordan',
'Maddison',
'Rylie',
'Alicia',
'Maeve',
'Margot',
'Kylee',
'Phoenix',
'Heidi',
'Zuri',
'Alondra',
'Lana',
'Madeleine',
'Gracelynn',
'Kenzie',
'Miracle',
'Shelby',
'Elle',
'Adrianna',
'Bianca',
'Addilyn',
'Kira',
'Veronica',
'Gwendolyn',
'Esmeralda',
'Chelsea',
'Alison',
'Skyler',
'Magnolia',
'Daphne',
'Jenna',
'Everleigh',
'Kyla',
'Braelynn',
'Harlow',
'Annalise',
'Mikayla',
'Dahlia',
'Maliyah',
'Averie',
'Scarlet',
'Kayleigh',
'Luciana',
'Kelsey',
'Nadia',
'Amber',
'Gia',
'Kamryn',
'Yaretzi',
'Carmen',
'Jimena',
'Erin',
'Christina',
'Katie',
'Ryan',
'Viviana',
'Alexia',
'Anaya',
'Serena',
'Katelyn',
'Ophelia',
'Regina',
'Helen',
'Remington',
'Camryn',
'Cadence',
'Royalty',
'Amari',
'Kathryn',
'Skye',
'Emely',
'Jada',
'Ariyah',
'Aylin',
'Saylor',
'Kendra',
'Cheyenne',
'Fernanda',
'Sabrina',
'Francesca',
'Eve',
'Mckinley',
'Frances',
'Sarai',
'Carolina',
'Kennedi',
'Nylah',
'Tatum',
'Alani',
'Lennon',
'Raven',
'Zariah',
'Leslie',
'Winter',
'Abby',
'Mabel',
'Sierra',
'April',
'Willa',
'Carly',
'Jolene',
'Rosemary',
'Aviana',
'Madelynn',
'Selah',
'Renata',
'Lorelei',
'Briana',
'Celeste',
'Wren',
'Charleigh',
'Leighton',
'Annabella',
'Jayleen',
'Braelyn',
'Ashlyn',
'Jazlyn',
'Mira',
'Oakley',
'Malaysia',
'Edith',
'Avianna',
'Maryam',
'Emmalyn',
'Hattie',
'Kensley',
'Macie',
'Bristol',
'Marlee',
'Demi',
'Cataleya',
'Maia',
'Sylvia',
'Itzel',
'Allyson',
'Lilith',
'Melany',
'Kaydence',
'Holly',
'Nayeli',
'Meredith',
'Nia',
'Liana',
'Megan',
'Justice',
'Bethany',
'Alejandra',
'Janelle',
'Elisa',
'Adelina',
'Ashlynn',
'Elianna',
'Aleah',
'Myra',
'Lainey',
'Blair',
'Kassidy',
'Charley',
'Virginia',
'Kara',
'Helena',
'Sasha',
'Julie',
'Michaela',
'Carter',
'Matilda',
'Kehlani',
'Henley',
'Maisie',
'Hallie',
'Jazmin',
'Priscilla',
'Marilyn',
'Cecelia',
'Danna',
'Colette',
'Baylee',
'Elliott',
'Ivanna',
'Cameron',
'Celine',
'Alayah',
'Hanna',
'Imani',
'Angelica',
'Emelia',
'Kalani',
'Alanna',
'Lorelai',
'Macy',
'Karina',
'Addyson',
'Aleena',
'Aisha',
'Johanna',
'Mallory',
'Leona',
'Mariam',
'Kynlee',
'Madilynn',
'Karen',
'Karla',
'Skyla',
'Beatrice',
'Dayana',
'Gloria',
'Milani',
'Savanna',
'Karsyn',
'Rory',
'Giuliana',
'Lauryn',
'Liberty',
'Galilea',
'Aubrie',
'Charli',
'Kyleigh',
'Brylee',
'Jillian',
'Anne',
'Haylee',
'Dallas',
'Azalea',
'Jayda',
'Tiffany',
'Avah',
'Shiloh',
'Bailee',
'Jazmine',
'Esme',
'Coraline',
'Madisyn',
'Elaine',
'Lilian',
'Kyra',
'Kaliyah',
'Kora',
'Octavia',
'Irene',
'Kelly',
'Lacey',
'Laurel',
'Adley',
'Anika',
'Janiyah',
'Dorothy',
'Sutton',
'Julieta',
'Kimber',
'Remy',
'Cassandra',
'Rebekah',
'Collins',
'Elliot',
'Emmy',
'Sloan',
'Hayley',
'Amalia',
'Jemma',
'Jamie',
'Melina',
'Leyla',
'Jaylah',
'Anahi',
'Jaliyah',
'Kailani',
'Harlee',
'Wynter',
'Saige',
'Alessia',
'Monica',
'Anya',
'Antonella',
'Emberly',
'Khaleesi',
'Ivory',
'Greta',
'Maren',
'Alena',
'Emory',
'Alaia',
'Cynthia',
'Addisyn',
'Alia',
'Lylah',
'Angie',
'Ariya',
'Alma',
'Crystal',
'Jayde',
'Aileen',
'Kinslee',
'Siena',
'Zelda',
'Katalina',
'Marie',
'Pearl',
'Reyna',
'Mae',
'Zahra',
'Kailey',
'Jessie',
'Tiana',
'Amirah',
'Madalyn',
'Alaya',
'Lilyana',
'Julissa',
'Armani',
'Lennox',
'Lillie',
'Jolie',
'Laney',
'Roselyn',
'Mara',
'Joelle',
'Rosa',
'Kaylani',
'Bridget',
'Liv',
'Oaklyn',
'Aurelia',
'Clarissa',
'Elyse',
'Marissa',
'Monroe',
'Kori',
'Elsa',
'Rosie',
'Amelie',
'Aitana',
'Aliza',
'Eileen',
'Poppy',
'Emmie',
'Braylee',
'Milana',
'Addilynn',
'Royal',
'Chaya',
'Frida',
'Bonnie',
'Amora',
'Stevie',
'Tatiana',
'Malaya',
'Mina',
'Emerie',
'Reign',
'Zaylee',
'Annika',
'Kenia',
'Linda',
'Kenna',
'Faye',
'Reina',
'Brittany',
'Marina',
'Astrid',
'Kadence',
'Mikaela',
'Jaelyn',
'Briar',
'Kaylie',
'Teresa',
'Bria',
'Hadassah',
'Lilianna',
'Guadalupe',
'Rayna',
'Chanel',
'Lyra',
'Noa',
'Zariyah',
'Laylah',
'Aubrielle',
'Aniya',
'Livia',
'Ellen',
'Meadow',
'Amiya',
'Ellis',
'Elora',
'Milan',
'Hunter',
'Princess',
'Leanna',
'Nathalie',
'Clementine',
'Nola',
'Tenley',
'Simone',
'Lina',
'Marianna',
'Martha',
'Sariah',
'Louisa',
'Noemi',
'Emmeline',
'Kenley',
'Belen',
'Erika',
'Myah',
'Lara',
'Amani',
'Ansley',
'Everlee',
'Maleah',
'Salma',
'Jaelynn',
'Kiera',
'Dulce',
'Nala',
'Natasha',
'Averi',
'Mercy',
'Penny',
'Ariadne',
'Deborah',
'Elisabeth',
'Zaria',
'Hana',
'Kairi',
'Yareli',
'Raina',
'Ryann',
'Lexie',
'Thalia',
'Karter',
'Annabel',
'Christine',
'Estella',
'Keyla',
'Adele',
'Aya',
'Estelle',
'Landry',
'Tori',
'Perla',
'Lailah',
'Miah',
'Rylan',
'Angelique',
'Avalynn',
'Romina',
'Ari',
'Jaycee',
'Jaylene',
'Kai',
'Louise',
'Mavis',
'Scarlette',
'Belle',
'Lea',
'Nalani',
'Rivka',
'Ayleen',
'Calliope',
'Dalary',
'Zaniyah',
'Kaelyn',
'Sky',
'Jewel',
'Joselyn',
'Madalynn',
'Paola',
'Giovanna',
'Isabela',
'Karlee',
'Aubriella',
'Azariah',
'Tinley',
'Dream',
'Claudia',
'Corinne',
'Erica',
'Milena',
'Aliana',
'Kallie',
'Alyson',
'Joyce',
'Tinsley',
'Whitney',
'Emilee',
'Paisleigh',
'Carolyn',
'Jaylee',
'Zoie',
'Frankie',
'Andi',
'Judith',
'Paula',
'Xiomara',
'Aiyana',
'Amia',
'Analia',
'Audrina',
'Hadlee',
'Rayne',
'Amayah',
'Cara',
'Celia',
'Lyanna',
'Opal',
'Amaris',
'Clare',
'Gwen',
'Giana',
'Veda',
'Alisha',
'Davina',
'Rhea',
'Sariyah',
'Noor',
'Danica',
'Kathleen',
'Lillianna',
'Lindsey',
'Maxine',
'Paulina',
'Hailee',
'Harleigh',
'Nancy',
'Jessa',
'Raquel',
'Raylee',
'Zainab',
'Chana',
'Lisa',
'Heavenly',
'Oaklynn',
'Aminah',
'Emmalynn',
'Patricia',
'India',
'Janessa',
'Paloma',
'Ramona',
'Sandra',
'Abril',
'Emmaline',
'Itzayana',
'Kassandra',
'Vienna',
'Marleigh',
'Kailyn',
'Novalee',
'Rosalyn',
'Hadleigh',
'Luella',
'Taliyah',
'Avalyn',
'Barbara',
'Iliana',
'Jana',
'Meilani',
'Aadhya',
'Alannah',
'Blaire',
'Brenda',
'Casey',
'Selene',
'Lizbeth',
'Adrienne',
'Annalee',
'Malani',
'Aliya',
'Miley',
'Nataly',
'Bexley',
'Joslyn',
'Maliah',
'Zion',
'Breanna',
'Melania',
'Estrella',
'Ingrid',
'Jayden',
'Kaya',
'Kaylin',
'Harmoni',
'Arely',
'Jazlynn',
'Kiana',
'Dana',
'Mylah',
'Oaklee',
'Ailani',
'Kailee',
'Legacy',
'Marjorie',
'Paityn',
'Courtney',
'Ellianna',
'Jurnee',
'Karlie',
'Evalyn',
'Holland',
'Kenya',
'Magdalena',
'Carla',
'Halle',
'Aryanna',
'Kaiya',
'Kimora',
'Naya',
'Saoirse',
'Susan',
'Desiree',
'Ensley',
'Renee',
'Esperanza',
'Treasure',
'Caylee',
'Ellison',
'Kristina',
'Adilynn',
'Anabelle',
'Egypt',
'Spencer',
'Tegan',
'Aranza',
'Vada',
'Emerald',
'Florence',
'Marlowe',
'Micah',
'Sonia',
'Sunny',
'Tara',
'Riya',
'Yara',
'Alisa',
'Nathalia',
'Yamileth',
'Saanvi',
'Samira',
'Sylvie',
'Brenna',
'Carlee',
'Jenny',
'Miya',
'Monserrat',
'Zendaya',
'Alora'
}

SetPlayerSkin.FamilyNames = {
'SMITH',
'JOHNSON',
'WILLIAMS',
'BROWN',
'JONES',
'GARCIA',
'MILLER',
'DAVIS',
'RODRIGUEZ',
'MARTINEZ',
'HERNANDEZ',
'LOPEZ',
'GONZALEZ',
'WILSON',
'ANDERSON',
'THOMAS',
'TAYLOR',
'MOORE',
'JACKSON',
'MARTIN',
'LEE',
'PEREZ',
'THOMPSON',
'WHITE',
'HARRIS',
'SANCHEZ',
'CLARK',
'RAMIREZ',
'LEWIS',
'ROBINSON',
'WALKER',
'YOUNG',
'ALLEN',
'KING',
'WRIGHT',
'SCOTT',
'TORRES',
'NGUYEN',
'HILL',
'FLORES',
'GREEN',
'ADAMS',
'NELSON',
'BAKER',
'HALL',
'RIVERA',
'CAMPBELL',
'MITCHELL',
'CARTER',
'ROBERTS',
'GOMEZ',
'PHILLIPS',
'EVANS',
'TURNER',
'DIAZ',
'PARKER',
'CRUZ',
'EDWARDS',
'COLLINS',
'REYES',
'STEWART',
'MORRIS',
'MORALES',
'MURPHY',
'COOK',
'ROGERS',
'GUTIERREZ',
'ORTIZ',
'MORGAN',
'COOPER',
'PETERSON',
'BAILEY',
'REED',
'KELLY',
'HOWARD',
'RAMOS',
'KIM',
'COX',
'WARD',
'RICHARDSON',
'WATSON',
'BROOKS',
'CHAVEZ',
'WOOD',
'JAMES',
'BENNETT',
'GRAY',
'MENDOZA',
'RUIZ',
'HUGHES',
'PRICE',
'ALVAREZ',
'CASTILLO',
'SANDERS',
'PATEL',
'MYERS',
'LONG',
'ROSS',
'FOSTER',
'JIMENEZ',
'POWELL',
'JENKINS',
'PERRY',
'RUSSELL',
'SULLIVAN',
'BELL',
'COLEMAN',
'BUTLER',
'HENDERSON',
'BARNES',
'GONZALES',
'FISHER',
'VASQUEZ',
'SIMMONS',
'ROMERO',
'JORDAN',
'PATTERSON',
'ALEXANDER',
'HAMILTON',
'GRAHAM',
'REYNOLDS',
'GRIFFIN',
'WALLACE',
'MORENO',
'WEST',
'COLE',
'HAYES',
'BRYANT',
'HERRERA',
'GIBSON',
'ELLIS',
'TRAN',
'MEDINA',
'AGUILAR',
'STEVENS',
'MURRAY',
'FORD',
'CASTRO',
'MARSHALL',
'OWENS',
'HARRISON',
'FERNANDEZ',
'MCDONALD',
'WOODS',
'WASHINGTON',
'KENNEDY',
'WELLS',
'VARGAS',
'HENRY',
'CHEN',
'FREEMAN',
'WEBB',
'TUCKER',
'GUZMAN',
'BURNS',
'CRAWFORD',
'OLSON',
'SIMPSON',
'PORTER',
'HUNTER',
'GORDON',
'MENDEZ',
'SILVA',
'SHAW',
'SNYDER',
'MASON',
'DIXON',
'MUNOZ',
'HUNT',
'HICKS',
'HOLMES',
'PALMER',
'WAGNER',
'BLACK',
'ROBERTSON',
'BOYD',
'ROSE',
'STONE',
'SALAZAR',
'FOX',
'WARREN',
'MILLS',
'MEYER',
'RICE',
'SCHMIDT',
'GARZA',
'DANIELS',
'FERGUSON',
'NICHOLS',
'STEPHENS',
'SOTO',
'WEAVER',
'RYAN',
'GARDNER',
'PAYNE',
'GRANT',
'DUNN',
'KELLEY',
'SPENCER',
'HAWKINS',
'ARNOLD',
'PIERCE',
'VAZQUEZ',
'HANSEN',
'PETERS',
'SANTOS',
'HART',
'BRADLEY',
'KNIGHT',
'ELLIOTT',
'CUNNINGHAM',
'DUNCAN',
'ARMSTRONG',
'HUDSON',
'CARROLL',
'LANE',
'RILEY',
'ANDREWS',
'ALVARADO',
'RAY',
'DELGADO',
'BERRY',
'PERKINS',
'HOFFMAN',
'JOHNSTON',
'MATTHEWS',
'PENA',
'RICHARDS',
'CONTRERAS',
'WILLIS',
'CARPENTER',
'LAWRENCE',
'SANDOVAL',
'GUERRERO',
'GEORGE',
'CHAPMAN',
'RIOS',
'ESTRADA',
'ORTEGA',
'WATKINS',
'GREENE',
'NUNEZ',
'WHEELER',
'VALDEZ',
'HARPER',
'BURKE',
'LARSON',
'SANTIAGO',
'MALDONADO',
'MORRISON',
'FRANKLIN',
'CARLSON',
'AUSTIN',
'DOMINGUEZ',
'CARR',
'LAWSON',
'JACOBS',
'OBRIEN',
'LYNCH',
'SINGH',
'VEGA',
'BISHOP',
'MONTGOMERY',
'OLIVER',
'JENSEN',
'HARVEY',
'WILLIAMSON',
'GILBERT',
'DEAN',
'SIMS',
'ESPINOZA',
'HOWELL',
'LI',
'WONG',
'REID',
'HANSON',
'LE',
'MCCOY',
'GARRETT',
'BURTON',
'FULLER',
'WANG',
'WEBER',
'WELCH',
'ROJAS',
'LUCAS',
'MARQUEZ',
'FIELDS',
'PARK',
'YANG',
'LITTLE',
'BANKS',
'PADILLA',
'DAY',
'WALSH',
'BOWMAN',
'SCHULTZ',
'LUNA',
'FOWLER',
'MEJIA',
'DAVIDSON',
'ACOSTA',
'BREWER',
'MAY',
'HOLLAND',
'JUAREZ',
'NEWMAN',
'PEARSON',
'CURTIS',
'CORTEZ',
'DOUGLAS',
'SCHNEIDER',
'JOSEPH',
'BARRETT',
'NAVARRO',
'FIGUEROA',
'KELLER',
'AVILA',
'WADE',
'MOLINA',
'STANLEY',
'HOPKINS',
'CAMPOS',
'BARNETT',
'BATES',
'CHAMBERS',
'CALDWELL',
'BECK',
'LAMBERT',
'MIRANDA',
'BYRD',
'CRAIG',
'AYALA',
'LOWE',
'FRAZIER',
'POWERS',
'NEAL',
'LEONARD',
'GREGORY',
'CARRILLO',
'SUTTON',
'FLEMING',
'RHODES',
'SHELTON',
'SCHWARTZ',
'NORRIS',
'JENNINGS',
'WATTS',
'DURAN',
'WALTERS',
'COHEN',
'MCDANIEL',
'MORAN',
'PARKS',
'STEELE',
'VAUGHN',
'BECKER',
'HOLT',
'DELEON',
'BARKER',
'TERRY',
'HALE',
'LEON',
'HAIL',
'BENSON',
'HAYNES',
'HORTON',
'MILES',
'LYONS',
'PHAM',
'GRAVES',
'BUSH',
'THORNTON',
'WOLFE',
'WARNER',
'CABRERA',
'MCKINNEY',
'MANN',
'ZIMMERMAN',
'DAWSON',
'LARA',
'FLETCHER',
'PAGE',
'MCCARTHY',
'LOVE',
'ROBLES',
'CERVANTES',
'SOLIS',
'ERICKSON',
'REEVES',
'CHANG',
'KLEIN',
'SALINAS',
'FUENTES',
'BALDWIN',
'DANIEL',
'SIMON',
'VELASQUEZ',
'HARDY',
'HIGGINS',
'AGUIRRE',
'LIN',
'CUMMINGS',
'CHANDLER',
'SHARP',
'BARBER',
'BOWEN',
'OCHOA',
'DENNIS',
'ROBBINS',
'LIU',
'RAMSEY',
'FRANCIS',
'GRIFFITH',
'PAUL',
'BLAIR',
'OCONNOR',
'CARDENAS',
'PACHECO',
'CROSS',
'CALDERON',
'QUINN',
'MOSS',
'SWANSON',
'CHAN',
'RIVAS',
'KHAN',
'RODGERS',
'SERRANO',
'FITZGERALD',
'ROSALES',
'STEVENSON',
'CHRISTENSEN',
'MANNING',
'GILL',
'CURRY',
'MCLAUGHLIN',
'HARMON',
'MCGEE',
'GROSS',
'DOYLE',
'GARNER',
'NEWTON',
'BURGESS',
'REESE',
'WALTON',
'BLAKE',
'TRUJILLO',
'ADKINS',
'BRADY',
'GOODMAN',
'ROMAN',
'WEBSTER',
'GOODWIN',
'FISCHER',
'HUANG',
'POTTER',
'DELACRUZ',
'MONTOYA',
'TODD',
'WU',
'HINES',
'MULLINS',
'CASTANEDA',
'MALONE',
'CANNON',
'TATE',
'MACK',
'SHERMAN',
'HUBBARD',
'HODGES',
'ZHANG',
'GUERRA',
'WOLF',
'VALENCIA',
'FRANCO',
'SAUNDERS',
'ROWE',
'GALLAGHER',
'FARMER',
'HAMMOND',
'HAMPTON',
'TOWNSEND',
'INGRAM',
'WISE',
'GALLEGOS',
'CLARKE',
'BARTON',
'SCHROEDER',
'MAXWELL',
'WATERS',
'LOGAN',
'CAMACHO',
'STRICKLAND',
'NORMAN',
'PERSON',
'COLON',
'PARSONS',
'FRANK',
'HARRINGTON',
'GLOVER',
'OSBORNE',
'BUCHANAN',
'CASEY',
'FLOYD',
'PATTON',
'IBARRA',
'BALL',
'TYLER',
'SUAREZ',
'BOWERS',
'OROZCO',
'SALAS',
'COBB',
'GIBBS',
'ANDRADE',
'BAUER',
'CONNER',
'MOODY',
'ESCOBAR',
'MCGUIRE',
'LLOYD',
'MUELLER',
'HARTMAN',
'FRENCH',
'KRAMER',
'MCBRIDE',
'POPE',
'LINDSEY',
'VELAZQUEZ',
'NORTON',
'MCCORMICK',
'SPARKS',
'FLYNN',
'YATES',
'HOGAN',
'MARSH',
'MACIAS',
'VILLANUEVA',
'ZAMORA',
'PRATT',
'STOKES',
'OWEN',
'BALLARD',
'LANG',
'BROCK',
'VILLARREAL',
'CHARLES',
'DRAKE',
'BARRERA',
'CAIN',
'PATRICK',
'PINEDA',
'BURNETT',
'MERCADO',
'SANTANA',
'SHEPHERD',
'BAUTISTA',
'ALI',
'SHAFFER',
'LAMB',
'TREVINO',
'MCKENZIE',
'HESS',
'BEIL',
'OLSEN',
'COCHRAN',
'MORTON',
'NASH',
'WILKINS',
'PETERSEN',
'BRIGGS',
'SHAH',
'ROTH',
'NICHOLSON',
'HOLLOWAY',
'LOZANO',
'FLOWERS',
'RANGEL',
'HOOVER',
'ARIAS',
'SHORT',
'MORA',
'VALENZUELA',
'BRYAN',
'MEYERS',
'WEISS',
'UNDERWOOD',
'BASS',
'GREER',
'SUMMERS',
'HOUSTON',
'CARSON',
'MORROW',
'CLAYTON',
'WHITAKER',
'DECKER',
'YODER',
'COLLIER',
'ZUNIGA',
'CAREY',
'WILCOX',
'MELENDEZ',
'POOLE',
'ROBERSON',
'LARSEN',
'CONLEY',
'DAVENPORT',
'COPELAND',
'MASSEY',
'LAM',
'HUFF',
'ROCHA',
'CAMERON',
'JEFFERSON',
'HOOD',
'MONROE',
'ANTHONY',
'PITTMAN',
'HUYNH',
'RANDALL',
'SINGLETON',
'KIRK',
'COMBS',
'MATHIS',
'CHRISTIAN',
'SKINNER',
'BRADFORD',
'RICHARD',
'GALVAN',
'WALL',
'BOONE',
'KIRBY',
'WILKINSON',
'BRIDGES',
'BRUCE',
'ATKINSON',
'VELEZ',
'MEZA',
'ROY',
'VINCENT',
'YORK',
'HODGE',
'VILLA',
'ABBOTT',
'ALLISON',
'TAPIA',
'GATES',
'CHASE',
'SOSA',
'SWEENEY',
'FARRELL',
'WYATT',
'DALTON',
'HORN',
'BARRON',
'PHELPS',
'YU',
'DICKERSON',
'HEATH',
'FOLEY',
'ATKINS',
'MATHEWS',
'BONILLA',
'ACEVEDO',
'BENITEZ',
'ZAVALA',
'HENSLEY',
'GLENN',
'CISNEROS',
'HARRELL',
'SHIELDS',
'RUBIO',
'CHOI',
'HUFFMAN',
'BOYER',
'GARRISON',
'ARROYO',
'BOND',
'KANE',
'HANCOCK',
'CALLAHAN',
'DILLON',
'CLINE',
'WIGGINS',
'GRIMES',
'ARELLANO',
'MELTON',
'ONEILL',
'SAVAGE',
'HO',
'BELTRAN',
'PITTS',
'PARRISH',
'PONCE',
'RICH',
'BOOTH',
'KOCH',
'GOLDEN',
'WARE',
'BRENNAN',
'MCDOWELL',
'MARKS',
'CANTU',
'HUMPHREY',
'BAXTER',
'SAWYER',
'CLAY',
'TANNER',
'HUTCHINSON',
'KAUR',
'BERG',
'WILEY',
'GILMORE',
'RUSSO',
'VILLEGAS',
'HOBBS',
'KEITH',
'WILKERSON',
'AHMED',
'BEARD',
'MCCLAIN',
'MONTES',
'MATA',
'ROSARIO',
'VANG',
'WALTER',
'HENSON',
'ONEAL',
'MOSLEY',
'MCCLURE',
'BEASLEY',
'STEPHENSON',
'SNOW',
'HUERTA',
'PRESTON',
'VANCE',
'BARRY',
'JOHNS',
'EATON',
'BLACKWELL',
'DYER',
'PRINCE',
'MACDONALD',
'SOLOMON',
'GUEVARA',
'STAFFORD',
'ENGLISH',
'HURST',
'WOODARD',
'CORTES',
'SHANNON',
'KEMP',
'NOLAN',
'MCCULLOUGH',
'MERRITT',
'MURILLO',
'MOON',
'SALGADO',
'STRONG',
'KLINE',
'CORDOVA',
'BARAJAS',
'ROACH',
'ROSAS',
'WINTERS',
'JACOBSON',
'LESTER',
'KNOX',
'BULLOCK',
'KERR',
'LEACH',
'MEADOWS',
'DAVILA',
'ORR',
'WHITEHEAD',
'PRUITT',
'KENT',
'CONWAY',
'MCKEE',
'BARR',
'DAVID',
'DEJESUS',
'MARIN',
'BERGER',
'MCINTYRE',
'BLANKENSHIP',
'GAINES',
'PALACIOS',
'CUEVAS',
'BARTLETT',
'DURHAM',
'DORSEY',
'MCCALL',
'ODONNELL',
'STEIN',
'BROWNING',
'STOUT',
'LOWERY',
'SLOAN',
'MCLEAN',
'HENDRICKS',
'CALHOUN',
'SEXTON',
'CHUNG',
'GENTRY',
'HULL',
'DUARTE',
'ELLISON',
'NIELSEN',
'GILLESPIE',
'BUCK',
'MIDDLETON',
'SELLERS',
'LEBLANC',
'ESPARZA',
'HARDIN',
'BRADSHAW',
'MCINTOSH',
'HOWE',
'LIVINGSTON',
'FROST',
'GLASS',
'MORSE',
'KNAPP',
'HERMAN',
'STARK',
'BRAVO',
'NOBLE',
'SPEARS',
'WEEKS',
'CORONA',
'FREDERICK',
'BUCKLEY',
'MCFARLAND',
'HEBERT',
'ENRIQUEZ',
'HICKMAN',
'QUINTERO',
'RANDOLPH',
'SCHAEFER',
'WALLS',
'TREJO',
'HOUSE',
'REILLY',
'PENNINGTON',
'MICHAEL',
'CONRAD',
'GILES',
'BENJAMIN',
'CROSBY',
'FITZPATRICK',
'DONOVAN',
'MAYS',
'MAHONEY',
'VALENTINE',
'RAYMOND',
'MEDRANO',
'HAHN',
'MCMILLAN',
'SMALL',
'BENTLEY',
'FELIX',
'PECK',
'LUCERO',
'BOYLE',
'HANNA',
'PACE',
'RUSH',
'HURLEY',
'HARDING',
'MCCONNELL',
'BERNAL',
'NAVA',
'AYERS',
'EVERETT',
'VENTURA',
'AVERY',
'PUGH',
'MAYER',
'BENDER',
'SHEPARD',
'MCMAHON',
'LANDRY',
'CASE',
'SAMPSON',
'MOSES',
'MAGANA',
'BLACKBURN',
'DUNLAP',
'GOULD',
'DUFFY',
'VAUGHAN',
'HERRING',
'MCKAY',
'ESPINOSA',
'RIVERS',
'FARLEY',
'BERNARD',
'ASHLEY',
'FRIEDMAN',
'POTTS',
'TRUONG',
'COSTA',
'CORREA',
'BLEVINS',
'NIXON',
'CLEMENTS',
'FRY',
'DELAROSA',
'BEST',
'BENTON',
'LUGO',
'PORTILLO',
'DOUGHERTY',
'CRANE',
'HALEY',
'PHAN',
'VILLALOBOS',
'BLANCHARD',
'HORNE',
'FINLEY',
'QUINTANA',
'LYNN',
'ESQUIVEL',
'BEAN',
'DODSON',
'MULLEN',
'XIONG',
'HAYDEN',
'CANO',
'LEVY',
'HUBER',
'RICHMOND',
'MOYER',
'LIM',
'FRYE',
'SHEPPARD',
'MCCARTY',
'AVALOS',
'BOOKER',
'WALLER',
'PARRA',
'WOODWARD',
'JARAMILLO',
'KRUEGER',
'RASMUSSEN',
'BRANDT',
'PERALTA',
'DONALDSON',
'STUART',
'FAULKNER',
'MAYNARD',
'GALINDO',
'COFFEY',
'ESTES',
'SANFORD',
'BURCH',
'MADDOX',
'VO',
'OCONNELL',
'VU',
'ANDERSEN',
'SPENCE',
'MCPHERSON',
'CHURCH',
'SCHMITT',
'STANTON',
'LEAL',
'CHERRY',
'COMPTON',
'DUDLEY',
'SIERRA',
'POLLARD',
'ALFARO',
'HESTER',
'PROCTOR',
'LU',
'HINTON',
'NOVAK',
'GOOD',
'MADDEN',
'MCCANN',
'TERRELL',
'JARVIS',
'DICKSON',
'REYNA',
'CANTRELL',
'MAYO',
'BRANCH',
'HENDRIX',
'ROLLINS',
'ROWLAND',
'WHITNEY',
'DUKE',
'ODOM',
'DAUGHERTY',
'TRAVIS',
'TANG',
'ARCHER'
}
SetPlayerSkin.PlayerSkins = {
    SetPlayerSkin(0, "A young black man in a black sleeveless t-shirt and blue jeans"),
    SetPlayerSkin(1, "An old white man in a red shirt with black and white plaids, khaki pants and with a red headband"),
    SetPlayerSkin(2, "A young white man in a white hoody, blue jeans and with a white hat"),
    -- SetPlayerSkin(3, "Andre"),                                           ---> not working
    -- SetPlayerSkin(4, "Barry \"Big Bear\" Thorne[Thin]"),                 ---> not working
    -- SetPlayerSkin(5, "Barry \"Big Bear\" Thorne[Big]"),                  ---> not working
    -- SetPlayerSkin(6, "Emmet"),                                           ---> not working
    SetPlayerSkin(7, "A young black man in a blue jeans jacket and beige pants"),
    -- SetPlayerSkin(8, "Janitor"),                                         ---> not working
    SetPlayerSkin(9, "An old black woman in a brown suit"),
    SetPlayerSkin(10, "An old woman in a red shirt with black plaid and a khaki skirt"),
    SetPlayerSkin(11, "A young black woman in a black suit without jacket"),
    SetPlayerSkin(12, "A young white woman in a black dress"),
    SetPlayerSkin(13, "A young black woman in a purple t-shirt, blue jeans and with a beige hat"),
    SetPlayerSkin(14, "An old bald black man in a colorful shirt and brown pants"),
    SetPlayerSkin(15, "An old bald black man in a white shirt with black plaid and blue jeans"),
    SetPlayerSkin(16, "A middle-aged black man in a black shirt and orange vest, black jeans and with a black cap and headphones"),
    SetPlayerSkin(17, "A middle-aged black man in a black suit"),
    SetPlayerSkin(18, "A young black man in red ang green shorts"),
    SetPlayerSkin(19, "A young black man in red pants and with a red head"),
    SetPlayerSkin(20, "A young white man in a yellow and black shirt and black pants"),
    SetPlayerSkin(21, "A young black man in a navy blue shirt with white stripes and khaki three quarter pants"),
    SetPlayerSkin(22, "A young black man in a black and orange hoody, black and orange pants and with a black hat"),
    SetPlayerSkin(23, "A young white man in a gray t-shirt, beige three quarter pants and with a black cap"),
    SetPlayerSkin(24, "A middle-aged black man in a navy blue jacket, blue jeans and navy blue cap"),
    SetPlayerSkin(25, "A middle-aged black man in a navy blue and white jacket and black jeans"),
    SetPlayerSkin(26, "A young white man in a navy blue t-shirt, beige shorts and with a gray backpack"),
    SetPlayerSkin(27, "A middle-aged white man in a white t-shirt, blue jeans, with a yellow hat and white gloves"),
    SetPlayerSkin(28, "A young black man in a brown sleeveless t-shirt, gray pants and with a brown hat"),
    SetPlayerSkin(29, "A middle-aged white man in a white hoody, blue jeans and with a black cap"),
    SetPlayerSkin(30, "A middle-aged white man in a gray sleeveless t-shirt, gray pants and with black glasses"),
    SetPlayerSkin(31, "A middle-aged white woman in a white t-shirt, blue jeans and with a white hat"),
    SetPlayerSkin(32, "An old white man in navy blue shirt, gray jeans and with a navy blue cap"),
    SetPlayerSkin(33, "A middle-aged white man in a black coat, black pants and with a black hat"),
    SetPlayerSkin(34, "A middle-aged white man in a blue shirt with gray plaid, blue jeans, with a gray hat and black glasses"),
    SetPlayerSkin(35, "A middle-aged white man in a pink shirt, beige three quarter pants and with a beige hat"),
    SetPlayerSkin(36, "A middle-aged white man in a white polo t-shirt, navy blue three quarter pants and with a navy blue cap"),
    SetPlayerSkin(37, "A middle-aged white man in a green polo t-shirt, khaki three quarter pants and with a red cap"),
    SetPlayerSkin(38, "An old white woman in a white and khaki shirt, khaki three quarter pants and with a pink headband cap"),
    SetPlayerSkin(39, "An old white woman in a brown sweater, navy blue skirt and with a blue and brown kerchief"),
    SetPlayerSkin(40, "A middle-aged white woman in a red dress"),
    SetPlayerSkin(41, "A young white woman in a light blue and white jacket, light blue and white pants and with a light blue hat"),
    -- SetPlayerSkin(42, "Jethro"),                                         ---> not working   
    SetPlayerSkin(43, "A middle-aged white man in a purple shirt, black pants and with black glasses"),
    SetPlayerSkin(44, "A middle-aged white man in a blue shirt with black plaid and brown jeans"),
    SetPlayerSkin(45, "A young white man in green shorts and with black glasses"),
    SetPlayerSkin(46, "A young white man in a white shirt and blue jeans"),
    SetPlayerSkin(47, "A young white man in a gray shirt with black plaid, beige pants and with black glasses"),
    SetPlayerSkin(48, "A young white man in a blue polo t-shirt with white stripes, gray pants and black glasses"),
    SetPlayerSkin(49, "An old white man in a black shirt with red vest and black and red pants"),
    SetPlayerSkin(50, "A white man in a gray overalls and with a black kerchief"),
    SetPlayerSkin(51, "A young black man in a orange sleeveless t-shirt, black shorts and with a black helmet"),
    SetPlayerSkin(52, "A young white man in orange and white shirt, black shorts and with a gray helmet"),
    SetPlayerSkin(53, "A middle-aged white woman in a khaki shirt, navy blue three quarter pants and a green headband cap"),
    SetPlayerSkin(54, "A middle-aged white woman in a brown sweater and a purple skirt"),
    SetPlayerSkin(55, "A young white woman in a black dress with brown strides and brown glasses"),
    SetPlayerSkin(56, "A young white woman in a green sleeveless t-shirt and a gray skirt"),
    SetPlayerSkin(57, "An old white man in a black suit"),
    SetPlayerSkin(58, "A middle-aged white man in a red shirt with black plaid and gray jeans"),
    SetPlayerSkin(59, "A young white man in a gray shirt with purple strides and black pants"),
    SetPlayerSkin(60, "A young white man in a brown sweater with blue jeans"),
    SetPlayerSkin(61, "A middle-aged white man in a black pilot suit"),
    SetPlayerSkin(62, "A old white man in a ligh blue with white stripes pajamas"),
    -- SetPlayerSkin(63, "A young black woman in a pink bra and black skirt"),  --> too vulgar...
    -- SetPlayerSkin(64, "A young white woman in a black t-shirt and pink skirt"),  --> too vulgar...
    SetPlayerSkin(65, "Kendl Johnson"),                                  ---> not working
    SetPlayerSkin(66, "A middle-aged black man in a navy blue and white jacket and black jeans"),
    -- SetPlayerSkin(67, "Pool Player"),                                    ---> same as 66
    SetPlayerSkin(68, "An old white man in a black suit"),
    SetPlayerSkin(69, "A young black woman in a sleeveless jeans shirt and blue jeans"),
    SetPlayerSkin(70, "An old white man in a white white coat and gray pants"),
    SetPlayerSkin(71, "A middle-aged white man in a blue shirt, navy blue pants and with a navy blue cap"),
    SetPlayerSkin(72, "A middle-aged white man in a blue shirt with black plaid and blue jeans"),
    SetPlayerSkin(73, "A middle-aged white man in a khaki t-shirt, camouflage pants and with a blue, red and white kerchief"),
    -- SetPlayerSkin(74, "-"),                                              ---> not working
    -- SetPlayerSkin(75, "Prostitute"),                                     ---> not working
    SetPlayerSkin(76, "A middle-aged black woman in a navy blue suit"),
    SetPlayerSkin(77, "A middle-aged white woman in a navy blue and green sweater, a khaki skirt and with a pink hat"),
    SetPlayerSkin(78, "An old white man in a red shirt with white plaid, blue jeans and with a navy blue cap and blue gloves"),
    SetPlayerSkin(79, "A middle-aged white man with a khaki jacket, blue pants and a navy blue hat"),
    SetPlayerSkin(80, "A middle-aged black man in red shorts and red boxing gloves"),
    -- SetPlayerSkin(81, "Boxer"),                                          ---> same as 80
    SetPlayerSkin(82, "A young white man in a black suit and with black glasses"),
    SetPlayerSkin(83, "A young black man in a white suit"),
    SetPlayerSkin(84, "A young black man in a blue suit and with black glasses"),
    -- SetPlayerSkin(85, "Prostitute"),                                     ---> same as 84
    -- SetPlayerSkin(86, "Ryder with robbery mask"),                        ---> not working
    -- SetPlayerSkin(87, "Stripper"),                                       ---> not working
    SetPlayerSkin(88, "An old woman in a red polo t-shirt and biege three quarter pants"),
    SetPlayerSkin(89, "An old woman in a ligh blue dress and with a red headband"),
    -- SetPlayerSkin(90, "A young woman in a brown t-shirt, a black skirt and with a green headband"),    --> too vulgar
    -- SetPlayerSkin(91, "Rich Woman"),                                     ---> same as 90
    -- SetPlayerSkin(92, "A young white woman in a navy blue swim suit"),             --> too vulgar
    SetPlayerSkin(93, "A young white woman in a black blouse and black jeans"),
    SetPlayerSkin(94, "An old white man in a white shirt, gray three quarter pants and a gray hat"),
    SetPlayerSkin(95, "An old man in a white shirt and blue jeans"),
    SetPlayerSkin(96, "A young white man in a white sleeveless t-shirt with gray strides and gray and red shorts"),
    SetPlayerSkin(97, "A young white man in red shorts"),
    SetPlayerSkin(98, "A young white man in a white shirt with a black vest and blue jeans"),
    -- SetPlayerSkin(99, "A young white man in a white t-shirt, black shorts and a gray helmet"),
    SetPlayerSkin(100, "A middle-aged white man with a long blonde tail, in a gray jacket, beige pants, with black glasses and brown gloves"),
    SetPlayerSkin(101, "A young white man with blonde hair, in a khaki jacket and white t-shirt, and black pants"),
    SetPlayerSkin(102, "A middle-aged black man with black hair, in a white t-shirt, purple shorts and with a purple headband"),
    SetPlayerSkin(103, "A middle-aged black man with a black jacket, black pants and with a purple kerchief"),
    SetPlayerSkin(104, "A middle-aged black man with a purple jacket, beige pants, with a black hat and glasses"),
    SetPlayerSkin(105, "A young black man in a green sweater, gray pants and with a green kerchief"),
    SetPlayerSkin(106, "A young black man with black long hair, green shirt with black strides and beige pants"),
    SetPlayerSkin(107, "A young black man in a green sleeveless t-shirt, black pants and with a black cap"),
    SetPlayerSkin(108, "A middle-aged white man in black pants and with a yellow headband"),
    SetPlayerSkin(109, "A middle-aged white man in a sleeveless white t-shirt, beige pants and with a yellow headband"),
    SetPlayerSkin(110, "A middle-aged white man in a sleeveless white t-shirt, navy blue three quarter pants and with a yellow headband"),
    SetPlayerSkin(111, "A middle-aged white man, black hair in a black suit"),
    SetPlayerSkin(112, "A middle-aged white bald man in a brown jacket, gray t-shirt and beige pants"),
    SetPlayerSkin(113, "A middle-aged white man with black hair and in a gray suit"),
    SetPlayerSkin(114, "A young white man in a gray polo with navy blue strides, gray pants and with a light blue headband"),
    SetPlayerSkin(115, "A young white man in a black jacket, white t-shirt, black pants and with a black cap, black glasses and a light blue headband"),
    SetPlayerSkin(116, "A young bald white man in a white t-shirt, beige three quarter pants and black glasses"),
    SetPlayerSkin(117, "A middle-aged asian man with black hair in a black suit"),
    SetPlayerSkin(118, "A middle-aged asian man with black hair in a black suit"),
    -- SetPlayerSkin(119, "Johhny Sindacco"),                                     ---> not working
    SetPlayerSkin(120, "A middle-aged white man with black hair in a gray suit with a black shirt"),
    SetPlayerSkin(121, "A bald middle-aged asian man in a white shirt with blue jeans, having tatoos on both arms"),
    SetPlayerSkin(122, "A young white man in a black t-shirt, khaki pants and with a black kerchief"),
    SetPlayerSkin(123, "A middle-aged white man with black hair, gray shirt with blue and yellow forms, black pants and with black glasses"),
    SetPlayerSkin(124, "A young white man with black hair in a black t-shirt and black pants"),
    SetPlayerSkin(125, "A middle-aged white man with black hair, in a black jacket and black pants"),
    -- SetPlayerSkin(126, "The Mafia"),                                        ---> same as 90
    SetPlayerSkin(127, "A middle-aged white man with brown hair, in a brown jacket with a light blue shirt, beige pants and with black gloves"),
    SetPlayerSkin(128, "A middle-aged white man with a long black hair in a khaki shirt and blue jeans"),
    SetPlayerSkin(129, "An old white woman with one tail white hair in a brown sweater with a brown skirt and with glasses"),
    SetPlayerSkin(130, "A middle-aged white woman with two tails brown hair in a navy blue shirt and a red skirt"),
    SetPlayerSkin(131, "A white woman with two tails brown hair in a brown t-shirt and blue jeans"),
    SetPlayerSkin(132, "A bald white man in a beige shirt, gray pants and with a red headband"),
    SetPlayerSkin(133, "A middle-aged white man with a gray tails in a khaki shirt, gray jeans and with a red cap"),
    SetPlayerSkin(134, "An old black man in a white shirt, gray shorts and with a khaki cap"),
    SetPlayerSkin(135, "An old white man with long white hair in a red shirt, khaki shorts and with a khaki winter hat"),
    SetPlayerSkin(136, "And old black man with one tail gray hair, gray sweater, purple pants and a red, green and yellow winter hat"),
    -- SetPlayerSkin(137, "A middle-aged man in a khaki t-shirt, blue three quarter jeans and with a box on head"),
    -- SetPlayerSkin(138, "White woman in a swim suit"),                       ---> TO DO
    -- SetPlayerSkin(139, "Black woman in a swim suit"),                       ---> TO DO
    -- SetPlayerSkin(140, "Asian woman in a swim suit"),                       ---> TO DO
    SetPlayerSkin(141, "A young asian woman with black hair in a black suit and with glasses"),
    SetPlayerSkin(142, "A middle-aged black man in a colorful t-shirt, black pants and with a colorful winter hat"),
    SetPlayerSkin(143, "A middle-aged black man in a light blue shirt, beige pants, with a white hat and black glasses"),
    SetPlayerSkin(144, "A young white man with black hair, black and white shirt, khaki pants and with a white mask"),
    -- SetPlayerSkin(145, "Crack Maker"),                                      ---> TO DO - naked woman!
    SetPlayerSkin(146, "A white young man with black hair in gray shorts"),       
    SetPlayerSkin(147, "A middle-aged white man with brown hair in a gray suit"),
    SetPlayerSkin(148, "A middle-aged black woman in a light blue suit"), --can't lay on ground (beach)
    -- SetPlayerSkin(149, "Big Smoke Armored"),                                ---> Not Working                              
    SetPlayerSkin(150, "A young white woman with one tails blonde hail, wearing a blue suit with gray stripes"),
    SetPlayerSkin(151, "A young white woman with brown hair, kakhi t-shirt, blue jeans skirt and glasses"),
    ---- SetPlayerSkin(152, "Prostitute"),
    -- SetPlayerSkin(153, "Construction Worker"),
    -- SetPlayerSkin(154, "Beach Visitor"),
    -- SetPlayerSkin(155, "Well Stacked Pizza Worker"),
    -- SetPlayerSkin(156, "Barber"),
    -- SetPlayerSkin(157, "Hillbilly"),
    -- SetPlayerSkin(158, "Farmer"),
    -- SetPlayerSkin(159, "Hillbilly"),
    -- SetPlayerSkin(160, "Hillbilly"),
    -- SetPlayerSkin(161, "Farmer"),
    -- SetPlayerSkin(162, "Hillbilly"),
    -- SetPlayerSkin(163, "Black Bouncer"),
    -- SetPlayerSkin(164, "White Bouncer"),
    -- SetPlayerSkin(165, "White MIB agent"),
    -- SetPlayerSkin(166, "Black MIB agent"),
    -- SetPlayerSkin(167, "Cluckin' Bell Worker"),
    -- SetPlayerSkin(168, "Hotdog / Chilli Dog Vendor"),
    -- SetPlayerSkin(169, "Normal Ped"),
    -- SetPlayerSkin(170, "Normal Ped"),
    -- SetPlayerSkin(171, "Blackjack Dealer"),
    -- SetPlayerSkin(172, "Casino croupier"),
    -- SetPlayerSkin(173, "San Fierro Rifa"),
    -- SetPlayerSkin(174, "San Fierro Rifa"),
    -- SetPlayerSkin(175, "San Fierro Rifa"),
    -- SetPlayerSkin(176, "Barber"),
    -- SetPlayerSkin(177, "Barber"),
    -- SetPlayerSkin(178, "Whore"),
    -- SetPlayerSkin(179, "Ammunation Salesman"),
    -- SetPlayerSkin(180, "Tattoo Artist"),
    -- SetPlayerSkin(181, "Punk"),
    -- SetPlayerSkin(182, "Cab Driver"),
    -- SetPlayerSkin(183, "Normal Ped"),
    -- SetPlayerSkin(184, "Normal Ped"),
    -- SetPlayerSkin(185, "Normal Ped"),
    -- SetPlayerSkin(186, "Normal Ped"),
    -- SetPlayerSkin(187, "Businessman"),
    -- SetPlayerSkin(188, "Normal Ped"),
    -- SetPlayerSkin(189, "Valet"),
    -- SetPlayerSkin(190, "Barbara Schternvart"),
    -- SetPlayerSkin(191, "Helena Wankstein"),
    -- SetPlayerSkin(192, "Michelle Cannes"),
    -- SetPlayerSkin(193, "Katie Zhan"),
    -- SetPlayerSkin(194, "Millie Perkins"),
    -- SetPlayerSkin(195, "Denise Robinson"),
    -- SetPlayerSkin(196, "Farm - Town inhabitant"),
    -- SetPlayerSkin(197, "Hillbilly"),
    -- SetPlayerSkin(198, "Farm - Town inhabitant"),
    -- SetPlayerSkin(199, "Farm - Town inhabitant"),
    -- SetPlayerSkin(200, "Hillbilly"),
    -- SetPlayerSkin(201, "Farmer"),
    -- SetPlayerSkin(202, "Farmer"),
    -- SetPlayerSkin(203, "Karate Teacher"),
    -- SetPlayerSkin(204, "Karate Teacher"),
    -- SetPlayerSkin(205, "Burger Shot Cashier"),
    -- SetPlayerSkin(206, "Cab Driver"),
    ---- SetPlayerSkin(207, "Prostitute"),
    -- SetPlayerSkin(208, "Su Xi Mu(Suzie)"),
    -- SetPlayerSkin(209, "Oriental Noodle stand vendor"),
    -- SetPlayerSkin(210, "Oriental Boating School Instructor"),
    -- SetPlayerSkin(211, "Clothes shop staff"),
    -- SetPlayerSkin(212, "Homeless"),
    -- SetPlayerSkin(213, "Weird old man"),
    -- SetPlayerSkin(214, "Waitress(Maria Latore)"),
    -- SetPlayerSkin(215, "Normal Ped"),
    -- SetPlayerSkin(216, "Normal Ped"),
    -- SetPlayerSkin(217, "Clothes shop staff"),
    -- SetPlayerSkin(218, "Normal Ped"),
    -- SetPlayerSkin(219, "Rich Woman"),
    -- SetPlayerSkin(220, "Cab Driver"),
    -- SetPlayerSkin(221, "Normal Ped"),
    -- SetPlayerSkin(222, "Normal Ped"),
    -- SetPlayerSkin(223, "Normal Ped"),
    -- SetPlayerSkin(224, "Normal Ped"),
    -- SetPlayerSkin(225, "Normal Ped"),
    -- SetPlayerSkin(226, "Normal Ped"),
    -- SetPlayerSkin(227, "Oriental Businessman"),
    -- SetPlayerSkin(228, "Oriental Ped"),
    -- SetPlayerSkin(229, "Oriental Ped"),
    -- SetPlayerSkin(230, "Homeless"),
    -- SetPlayerSkin(231, "Normal Ped"),
    -- SetPlayerSkin(232, "Normal Ped"),
    -- SetPlayerSkin(233, "Normal Ped"),
    -- SetPlayerSkin(234, "Cab Driver"),
    -- SetPlayerSkin(235, "Normal Ped"),
    -- SetPlayerSkin(236, "Normal Ped"),
    ---- SetPlayerSkin(237, "Prostitute"),
    ---- SetPlayerSkin(238, "Prostitute"),
    -- SetPlayerSkin(239, "Homeless"),
    -- SetPlayerSkin(240, "The D.A"),
    -- SetPlayerSkin(241, "Afro - American"),
    -- SetPlayerSkin(242, "Mexican"),
    ---- SetPlayerSkin(243, "Prostitute"),
    -- SetPlayerSkin(244, "Stripper"),
    ---- SetPlayerSkin(245, "Prostitute"),
    -- SetPlayerSkin(246, "Stripper"),
    -- SetPlayerSkin(247, "Biker"),
    -- SetPlayerSkin(248, "Biker"),
    -- SetPlayerSkin(249, "Pimp"),
    -- SetPlayerSkin(250, "Normal Ped"),
    -- SetPlayerSkin(251, "Lifeguard"),
    -- SetPlayerSkin(252, "Naked Valet"),
    -- SetPlayerSkin(253, "Bus Driver"),
    -- SetPlayerSkin(254, "Biker Drug Dealer"),
    -- SetPlayerSkin(255, "Chauffeur(Limo Driver)"),
    -- SetPlayerSkin(256, "Stripper"),
    -- SetPlayerSkin(257, "Stripper"),
    -- SetPlayerSkin(258, "Heckler"),
    -- SetPlayerSkin(259, "Heckler"),
    -- SetPlayerSkin(260, "Construction Worker"),
    -- SetPlayerSkin(261, "Cab driver"),
    -- SetPlayerSkin(262, "Cab driver"),
    -- SetPlayerSkin(263, "Normal Ped"),
    -- SetPlayerSkin(264, "Clown(Ice - cream Van Driver)"),
    -- SetPlayerSkin(265, "Officer Frank Tenpenny(Corrupt Cop)"),
    -- SetPlayerSkin(266, "Officer Eddie Pulaski(Corrupt Cop)"),
    -- SetPlayerSkin(267, "Officer Jimmy Hernandez"),
    -- SetPlayerSkin(268, "Dwaine / Dwayne"),
    -- SetPlayerSkin(269, "Melvin \"Big Smoke\" Harris"),
    -- SetPlayerSkin(270, "Sean 'Sweet' Johnson"),
    -- SetPlayerSkin(271, "Lance 'Ryder' Wilson"),
    -- SetPlayerSkin(272, "Mafia Boss"),
    -- SetPlayerSkin(273, "T - Bone Mendez"),
    -- SetPlayerSkin(274, "Paramedic(Emergency Medical Technician)"),
    -- SetPlayerSkin(275, "Paramedic(Emergency Medical Technician)"),
    -- SetPlayerSkin(276, "Paramedic(Emergency Medical Technician)"),
    -- SetPlayerSkin(277, "Firefighter"),
    -- SetPlayerSkin(278, "Firefighter"),
    -- SetPlayerSkin(279, "Firefighter"),
    -- SetPlayerSkin(280, "Los Santos Police Officer"),
    -- SetPlayerSkin(281, "San Fierro Police Officer"),
    -- SetPlayerSkin(282, "Las Venturas Police Officer"),
    -- SetPlayerSkin(283, "County Sheriff"),
    -- SetPlayerSkin(284, "LSPD Motorbike Cop"),
    -- SetPlayerSkin(285, "S.W.A.T Special Forces"),
    -- SetPlayerSkin(286, "Federal Agent"),
    -- SetPlayerSkin(287, "San Andreas Army"),
    -- SetPlayerSkin(288, "Desert Sheriff"),
    -- SetPlayerSkin(289, "Zero"),
    -- SetPlayerSkin(290, "Ken Rosenberg"),
    -- SetPlayerSkin(291, "Kent Paul"),
    -- SetPlayerSkin(292, "Cesar Vialpando"),
    -- SetPlayerSkin(293, "Jeffery \"OG Loc\" Martin / Cross"),
    -- SetPlayerSkin(294, "Wu Zi Mu(Woozie)"),
    -- SetPlayerSkin(295, "Michael Toreno"),
    -- SetPlayerSkin(296, "Jizzy B."),
    -- SetPlayerSkin(297, "Madd Dogg"),
    -- SetPlayerSkin(298, "Catalina"),
    -- SetPlayerSkin(299, "Claude Speed"),
    -- SetPlayerSkin(300, "Los Santos Police Officer(Without gun holster)"),
    -- SetPlayerSkin(301, "San Fierro Police Officer(Without gun holster)"),
    -- SetPlayerSkin(302, "Las Venturas Police Officer(Without gun holster)"),
    -- SetPlayerSkin(303, "Los Santos Police Officer(Without uniform)"),
    -- SetPlayerSkin(304, "Los Santos Police Officer(Without uniform)"),
    -- SetPlayerSkin(305, "Las Venturas Police Officer(Without uniform)"),
    -- SetPlayerSkin(306, "Los Santos Police Officer"),
    -- SetPlayerSkin(307, "San Fierro Police Officer"),
    -- SetPlayerSkin(308, "San Fierro Paramedic(Emergency Medical Technician)"),
    -- SetPlayerSkin(309, "Las Venturas Police Officer"),
    -- SetPlayerSkin(310, "Country Sheriff(Without hat)"),
    -- SetPlayerSkin(311, "Desert Sheriff(Without hat)")
}

function SetPlayerSkin:Apply(...)
    self.isTaken = true
    local player = self.Performer
    if not player then
        player = self.TargetItem
    end
    player:setModel(self.Id)
    player:setData('skinDescription', self.Description)
    
    if string.match(self.Description, "woman") then
        playerGenderNominative = "she"
        playerGenderGenitive = "her"
        player:setData('first_name', PickRandom(SetPlayerSkin.FemaleNames))
    else
        player:setData('first_name', PickRandom(SetPlayerSkin.MaleNames))
        playerGenderNominative = "he"
        playerGenderGenitive = "his"
    end
    player:setData('surname', PickRandom(SetPlayerSkin.FamilyNames))
    player:setData('name', player:getData('first_name')..' '..player:getData('surname'))

    player:setData('genderNominative', playerGenderNominative)
    player:setData('genderGenitive', playerGenderGenitive)

    --TODO: log atomic event here
    local event = {id = player:getData('id'), Name = player:getData('name'), Description = player:getData('skinDescription'), Gender = player:getData('genderNominative')}
    GRAPH.AtomicEvents[event.id] = event
end

function SetPlayerSkin:GetDynamicString()
    return 'return SetPlayerSkin('..self.Id..', "'..self.Description..'")'
end